### ISSUE TITLE
vcpkg autcomplete bash stdout in binary mode

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10596]
vcpkg autcomplete bash stdout should be in binary mode
Output  `\n` instead of `\r\n`

![image](https://user-images.githubusercontent.com/791115/77840804-e2707580-71bd-11ea-9631-3b958b32eebe.png)

Steps to reproduce:
Assume vcpkg is in `C:\vcpkg`
Open Msys2 bash
```bash
cd /C/vcpkg
. scripts/vcpkg_completion.bash
./vcpkg install libf<Press tab>
```

**Comment by JackBoosY** [comment]
Does this change affect what is displayed when using powershell?

**Comment by linquize** [comment]
No problem in powershell

**Comment by JackBoosY** [comment]
Should be fixed.

**Comment by linquize** [comment]
No, it is not fixed! trailing `^M` still present.

**Comment by linquize** [comment]
No, it is not fixed! Trailing ^M still present.
Please re-open this issue.

**Comment by JonLiu1993** [comment]
@linquiz, sorry for replying to you so late, I followed your steps to reproduce and got different results, can you see where it is different from yours?

- open gitbash
- . scripts/vcpkg_completion.bash
- ./vcpkg install libf<Press tab>

![image](https://user-images.githubusercontent.com/63675417/206132642-06f8edc5-dd5e-408d-9e9a-e477ec506541.png)

**Comment by linquize** [comment]
This is because Git Bash from Git for Windows misses some files about bash completion.

**Comment by linquize** [comment]
https://github.com/git-for-windows/git/issues/2562

**Comment by LilyWangLL** [comment]
Since this is a issue about Git, so I am closing this issue for now.
