### ISSUE TITLE
CMake find_package cannot always find packages

### ISSUE THREAD

**Issue by sryze** [microsoft/vcpkg#11247]
CMake cannot find packages that I install with vcpkg. I do specify the toolchain file path via CMAKE_TOOLCHAIN_FILE but it doesn't seem to work. Packages that I have this problem with:

* wxwidgets
* openjpeg

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019
- Latest vcpkg from master
- CMake version: 3.17.1

**To Reproduce**
1. vcpkg install openjpeg wxwidgets
2. create CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.0)

project(myproject)

find_package(OpenJPEG CONFIG REQUIRED)

find_package(wxWidgets REQUIRED)
include(${wxWidgets_USE_FILE})
```

3. cmake path/to/project  -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=E:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
(my vcpkg is instaled in E:\Tools\vcpkg)

Tried with both x64 and x86 - same result.

**Expected behavior**
Expected CMake to find OpenJPEG.

**Failure logs** 
```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.7601.
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "OpenJPEG" with any
  of the following names:

    OpenJPEGConfig.cmake
    openjpeg-config.cmake

  Add the installation prefix of "OpenJPEG" to CMAKE_PREFIX_PATH or set
  "OpenJPEG_DIR" to a directory containing one of the above files.  If
  "OpenJPEG" provides a separate development package or SDK, be sure it has
  been installed.
```

```
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)
```

**Comment by JackBoosY** [comment]
Do you have multiple vcpkg directories on your machine and use integrate function at the same time?

**Comment by sryze** [comment]
No, I have only one vcpkg installation

**Comment by JackBoosY** [comment]
@sryze Please clean cmake cache and try again.
I met this issue occasionally.

**Comment by sryze** [comment]
You mean CMake cache? already tried that - no luck

**Comment by FranciscoPombal** [comment]
@sryze 
I think you're having the same package discovery problem I had, I fixed it by passing `-DVCPKG_TARGET_TRIPLET=x64-windows-static` (adjust according to the triplet you're using).

I think this should be documented more clearly here: https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md
Currently it's only mentioned in the bottom of this document: https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md

It does not really make it clear that most of the time one wants to specify the triplet, otherwise the build will fail or presumably use some unexpected default triplet when multiple are installed side-by-side for the same library.

**Comment by sryze** [comment]
I've wiped my vcpkg directory with git clean and re-installed these 2 packages - now OpenJPEG is successfully found, but the problem persists with wxWidgets... I guess it's 2 different issues

**Comment by JackBoosY** [comment]
@sryze Yeah, that's right because `FindWxWidgets.cmake` does not exist.

**Comment by sryze** [comment]
FindwxWidgets.cmake is shipped with cmake itself

**Comment by JackBoosY** [comment]
@sryze Yes, but I'm not sure why it failed.
@strega-nil Could you please take a look?

Thanks.

**Comment by AbanoubNassem** [comment]
I have the same issue, did you fix it?

**Comment by sryze** [comment]
Unfortunately no, I didn't find a solution.

Looking at FindwxWidgets.cmake, I see that it searches for include/wx/wx.h to find the root directory of wxWidgets, but in my case it fails to find that file.

I added some debug logging in FindwxWidgets.cmake and vcpkg.cmake, below is the output:

```
CMAKE_PREFIX_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
CMAKE_LIBRARY_PATH=E:/Tools/vcpkg/installed/x64-windows/debug/lib/manual-link;E:/Tools/vcpkg/installed/x64-windows/lib/manual-link
CMAKE_FIND_ROOT_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
The C compiler identification is MSVC 19.26.28805.0
The CXX compiler identification is MSVC 19.26.28805.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
CMAKE_PREFIX_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
CMAKE_LIBRARY_PATH=E:/Tools/vcpkg/installed/x64-windows/debug/lib/manual-link;E:/Tools/vcpkg/installed/x64-windows/lib/manual-link
CMAKE_FIND_ROOT_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe -- works
Detecting C compiler ABI info
CMAKE_PREFIX_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
CMAKE_LIBRARY_PATH=E:/Tools/vcpkg/installed/x64-windows/debug/lib/manual-link;E:/Tools/vcpkg/installed/x64-windows/lib/manual-link
CMAKE_FIND_ROOT_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
CMAKE_PREFIX_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
CMAKE_LIBRARY_PATH=E:/Tools/vcpkg/installed/x64-windows/debug/lib/manual-link;E:/Tools/vcpkg/installed/x64-windows/lib/manual-link
CMAKE_FIND_ROOT_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe -- works
Detecting CXX compiler ABI info
CMAKE_PREFIX_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
CMAKE_LIBRARY_PATH=E:/Tools/vcpkg/installed/x64-windows/debug/lib/manual-link;E:/Tools/vcpkg/installed/x64-windows/lib/manual-link
CMAKE_FIND_ROOT_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_FIND_COMPONENTS : 
wxWidgets_FIND_STYLE=win32
CMAKE_PREFIX_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
CMAKE_LIBRARY_PATH=E:/Tools/vcpkg/installed/x64-windows/debug/lib/manual-link;E:/Tools/vcpkg/installed/x64-windows/lib/manual-link
CMAKE_FIND_ROOT_PATH=E:/Tools/vcpkg/installed/x64-windows/debug;E:/Tools/vcpkg/installed/x64-windows
WX_ROOT_DIR=E:/Tools/vcpkg/installed/x64-windows
WX_ROOT_DIR=E:/Tools/vcpkg/installed/x64-windows
WX_LIB_DIR=wxWidgets_LIB_DIR-NOTFOUND
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_FOUND           : FALSE
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_INCLUDE_DIRS    : 
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_LIBRARY_DIRS    : 
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_LIBRARIES       : 
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_CXX_FLAGS       : 
C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake(167): wxWidgets_USE_FILE        : C:/Program Files/CMake/share/cmake-3.15/Modules/UsewxWidgets.cmake
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindwxWidgets.cmake:1004 (find_package_handle_standard_args)
  E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:332 (_find_package)
  CMakeLists.txt:7 (find_package)


Configuring incomplete, errors occurred!
```

```
$ find . -name wx.h
./buildtrees/wxwidgets/src/v3.1.3-91ca46db88/include/wx/wx.h
./buildtrees/wxwidgets/src/v3.1.3-d3ae26deac/include/wx/wx.h
./installed/x64-windows/include/wx/wx.h
./installed/x64-windows-static/include/wx/wx.h
./installed/x86-windows/include/wx/wx.h
./installed/x86-windows-static/include/wx/wx.h
./packages/wxwidgets_x64-windows/include/wx/wx.h
./packages/wxwidgets_x64-windows-static/include/wx/wx.h
./packages/wxwidgets_x86-windows/include/wx/wx.h
./packages/wxwidgets_x86-windows-static/include/wx/wx.h
```

**Comment by AbanoubNassem** [comment]
well somehow the script is not loading my custom path variable rather loading the system path, so adding `WXWIN` variable in your system variables where it points to the root of the wxWidgets should fix all the issues , at least that what happened to me , hope this helps you.

**Comment by sryze** [comment]
@AbanoubNassem thanks. I ended up installing wxWidgets binaries manually (downloaded from the site) and defined WXWIN. CMake was able to find the libs after that.

**Comment by xahon** [comment]
I have the same issue too

**Comment by LegalizeAdulthood** [comment]
wxWidgets generates a setup.h file that describes all the build time choices made when building wxWidgets.  The CMake find module for wxWidgets in cmake 3.18.4 does this:

      find_path(wxWidgets_LIB_DIR
        NAMES
          qtu/wx/setup.h
          qtud/wx/setup.h
          msw/wx/setup.h
          mswd/wx/setup.h
          mswu/wx/setup.h
          mswud/wx/setup.h
          mswuniv/wx/setup.h
          mswunivd/wx/setup.h
          mswunivu/wx/setup.h
          mswunivud/wx/setup.h
        PATHS
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVER}_xp${_WX_ARCH}_lib   # prefer static
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVER}${_WX_ARCH}_lib   # prefer static
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVERx}_xp${_WX_ARCH}_lib   # prefer static
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVERx}${_WX_ARCH}_lib   # prefer static
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_ARCH}_lib                 # prefer static
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVER}_xp${_WX_ARCH}_dll
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVER}${_WX_ARCH}_dll
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVERx}_xp${_WX_ARCH}_dll
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_TOOLVERx}${_WX_ARCH}_dll
        ${WX_ROOT_DIR}/lib/${_WX_TOOL}${_WX_ARCH}_dll
        DOC "Path to wxWidgets libraries"
        NO_DEFAULT_PATH
        )

For Windows builds, we should have a mswd/wx/setup.h, etc.  However the package deployed by vcpkg doesn't contain a setup.h in these folders.  Attached is a small .zip that reproduces the issue using a manifest.
[example-wxwidgets.zip](https://github.com/microsoft/vcpkg/files/5674860/example-wxwidgets.zip)

**Comment by LegalizeAdulthood** [comment]
For wxwidgets, I believe this was broken by this pull request that moved the setup.h file from it's expected folder.

https://github.com/microsoft/vcpkg/pull/4846

**Comment by JackBoosY** [comment]
@LegalizeAdulthood That's another issue, I think.

**Comment by JackBoosY** [comment]
```
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
```
I think this issue is related to the external cmake.

**Comment by jafristr** [comment]
Is this issue still open? I'm seeing it on both of the PCs I've tried with every tutorial I've tried: 
The packages I've tried: sqlite3, grpc, raylib. 

My environment:
* OS: Windows
* Compilers available on system: both PCs have both VS2017 and 2019 (but I didn't even get to the point of opening the builds with them)
* vcpkg "2020.11" (I've also tried the latest, March 12, 2021)
* cmake version 3.19.6

My repro looks like sryze's except with different packages.

**Comment by jafristr** [comment]
Ah, sqlite3 was the triplet thing. Guess that's a vote for clearer docs. This tutorial https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/ says you _can_ choose different targets but it doesn't say it won't work if you don't.

**Comment by wbuck** [comment]
Yeah I'm currently also having this issue with `libuv` (I'm using the `vcpkg` manifest).

**Comment by LessonStudio** [comment]
When this happens it means that my x64 compiled vcpkg is not working with my unintendedly x86 executable. Easy fix. Change executable to x64 and all is good.

**Comment by stones314** [comment]
I have this problem with grpc.
I have made a CMakeLists.txt with this content:

------
cmake_minimum_required(VERSION 3.5.1)

project(grpcTest C CXX)

#Include vcpkg stuff so that we find installed gRPC things
set(CMAKE_TOOLCHAIN_FILE "C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake")

#Find gRPC:
find_package(grpc CONFIG REQUIRED)
--------
IT fails when it try to find the grpc package, complaining that it cant find grpcconfig.cmake.

In the CMake gui I select x64 platform.

using vcpkg list I see that grpc:x64-windows is listed

**Comment by JackBoosY** [comment]
@stones314  Did you use vcpkg toolchain?

**Comment by dg0yt** [comment]
@stones314 When using vcpkg as a submodule, `vcpkg.cmake` must be included *before* the first call to `project()`. Cf. [README](https://github.com/microsoft/vcpkg#vcpkg-as-a-submodule).

**Comment by stones314** [comment]
Thanks, it worked when I moved it before the project() call!

**Comment by dg0yt** [comment]
Regarding the other cases of "CMake find_package cannot always find packages":
IIUC vcpkg's cmake wrappers will only be activated for dependencies explicitly declared in a `vcpkg.json` manifest in your project.
Without the wrappers, `find_package()` will not always find the vcpkg package.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by bartvbl** [comment]
For anyone landing here from google having a similar issue: I was using the -DCMAKE_TOOLCHAIN_FILE= command line parameter before, which did not work despite the packages having been installed using the correct architecture triplets. Instead specifying the toolchain before the project() call as listed in @stones314 's comment solved my problems.

**Comment by dg0yt** [comment]
@bartvbl  `-DCMAKE_TOOLCHAIN_FILE=` work as can be expected from cmake: *before the first `project()` call*. If you forget it on the first call to cmake, you have to restart from an empyt build dir.

**Comment by bartvbl** [comment]
@dg0yt Thanks, I cleared the cache between every run because I just don't trust it to not cause lingering errors. Maybe there's something weird with my setup, but for some reason the command line parameter did nothing, while inserting the call before the project() call inside CMakeLists.txt worked as expected.

**Comment by dg0yt** [comment]
@bartvbl Well, There is an automated test which relies on the `-DCMAKE_TOOLCHAIN_FILE=` behaviour.
There are various reasons for `find_package` to fail, even in this issue. I intentionally wrote "restart from an empty build dir" because people sometimes meant different things by "clearing the cache".
`CMAKE_TOOLCHAIN_FILE` is a user option. IMO it doesn't belong into project files.

**Comment by RealTimeChris** [comment]
Hey guys! SO I think I may have found a solution... I was having the same issue and I changed my code to `include(path/to/vcpkg.cmake)` instead of adding it via CMAKE_TOOLCHAIN_FILE. As can be seen here...
https://github.com/RealTimeChris/Bot-Template-for-DiscordCoreAPI/blob/main/CMakeLists.txt#L13
