### ISSUE TITLE
[assimp] Assimp-vc142-mt cannot be found in VS2019

### ISSUE THREAD

**Issue by FloreauLuca** [microsoft/vcpkg#11352]
**Describe the bug**
I try to integrate assimp in a CMAKE project but vcpkg install **assimp-vc141-mt** and CMake try to access **assimp-vc142-mt** .

**Environment**
- OS: Windows 10
- Compiler: MSVC2019
- CMake 3.17.2

**To Reproduce**
1. ./vcpkg install assimp
2. add in CMakeList : 
```
   find_package(assimp CONFIG REQUIRED)
   target_link_libraries(COMMON PUBLIC assimp::assimp)
```
3. Generate

**Failure logs** 

```
-CMake Error at D:/App/vcpkg/installed/x64-windows/share/assimp/assimpTargets.cmake:86 (message):
  The imported target "assimp::assimp" references the file

     D:/App/vcpkg/installed/x64-windows/debug/lib/assimp-vc142-mtd.lib

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     D:/App/vcpkg/installed/x64-windows/share/assimp/assimpTargets.cmake

  but not all the files it references.

Call Stack (most recent call first):
  D:/App/vcpkg/installed/x64-windows/share/assimp/assimp-config.cmake:1 (include)
  D:/App/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:17 (find_package)

```

**Expected behavior**
- vcpkg install **assimp-vc142-mt** or CMake try to access  **assimp-vc141-mt**

**Comment by NancyLi1013** [comment]
Hi @FloreauLuca 
Thanks for posting this issue.

It seems that `assimp ` has some problems with Visual Studio 2019.

```
    elseif( MSVC_VERSION LESS 1910)
      set(MSVC_PREFIX "vc140")
    elseif( MSVC_VERSION LESS 1920)
      set(MSVC_PREFIX "vc141")
    elseif( MSVC_VERSION LESS 1930)
      set(MSVC_PREFIX "vc142")
```
I tried to print out the values of some variables:

```
MSVC_VERSION:1925
MSVC_PREFIX:vc141
LIBRARY_SUFFIX:-vc141-mt
OUTPUT_NAME:-vc141-mt
```

Upstream issue #https://github.com/assimp/assimp/issues/3210

**Comment by NancyLi1013** [comment]
Hi @FloreauLuca 

I submitted a PR to fix this issue.

Could you please help confirm if this can work for you?

**Comment by pisiiki** [comment]
I have tested it. It works. There are still some problems with missing IrrXML symbols btw.

**Comment by psionic12** [comment]
It works

**Comment by NancyLi1013** [comment]
Thanks for your feedback about this.
@pisiiki 
Could you please post the error info and also provide the project case?

**Comment by FloreauLuca** [comment]
The fix didn't fix the problem.
I update Visual Studio from 16.4.4 to 16.6.0 and it fix the problem.

**Comment by NancyLi1013** [comment]
Thanks for your update @FloreauLuca 
I will check this on my local.

**Comment by NancyLi1013** [comment]
Since it has been fixed by Visual Studio 2019 16.6.0. I'm closing this issue for now.

**Comment by psionic12** [comment]
Hi everyone, I use Clion instead of Visual Studio, and this issue still bother me.

**Comment by nmellado** [comment]
How do we do when we cannot use VS 16.6 (e.g. when compiling using github actions) ?

**Comment by NancyLi1013** [comment]
You might try the way as mentioned in this PR #11439.
