### ISSUE TITLE
[openblas] Installed package is broken

### ISSUE THREAD

**Issue by willyd** [Microsoft/vcpkg#1249]
After installing the vcpkg openblas port the cblas.h file is missing all the semi colons.

[Original File](https://github.com/Microsoft/vcpkg/files/1062880/cblas.h.original.txt)
[Installed File](https://github.com/Microsoft/vcpkg/files/1062883/cblas.h.installed.txt)

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

I believe I've fixed it with fbf40608, port version v0.2.19-2 (the installed cblas.h has semicolons).

**Comment by jasjuang** [comment]
Openblas is still broken for me, please see below error message

``````
C:\dev\vcpkg>vcpkg.exe install openblas
The following packages will be built and installed:
    openblas:x86-windows
Building package openblas:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/dev/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/dev/vcpkg/packages/openblas_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/dev/vcpkg/buildtrees/openblas
-- CURRENT_PORT_DIR=C:/dev/vcpkg/ports/openblas/.
CMake Error at ports/openblas/portfile.cmake:17 (message):
  openblas can only be built for x64 currently
Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)


Error: Building package openblas:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x86-windows
  Vcpkg version: 0.0.81-fbf406083ea34a8b090d7bc0e94180ff091b52de

Additionally, attach any relevant sections from the log files above.

C:\dev\vcpkg>
``````

I am able to install other packages like hdf5 and gflags without an issue so my vcpkg should be working properly.

**Comment by KindDragon** [comment]
```
CMake Error at ports/openblas/portfile.cmake:17 (message):
  openblas can only be built for x64 currently
```

**Comment by jasjuang** [comment]
oops yes x64 version works, thank you for your time

**Comment by stiv-yakovenko** [comment]
I have same problem with dlib:

```
C:\Users\steve\Projects\vcpkg>vcpkg install dlib
The following packages will be built and installed:
  * clapack[core]:x86-windows
    dlib[core]:x86-windows
  * fftw3[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libpng[core]:x86-windows
  * openblas[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: openblas:x86-windows
Building package openblas[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/steve/Projects/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/steve/Projects/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/steve/Projects/vcpkg/packages/openblas_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/steve/Projects/vcpkg/buildtrees/openblas
-- CURRENT_PORT_DIR=C:/Users/steve/Projects/vcpkg/ports/openblas
CMake Error at ports/openblas/portfile.cmake:16 (message):
  openblas can only be built for x64 currently
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)


Error: Building package openblas:x86-windows failed with: BUILD_FAILED
```

how can i fix it?

**Comment by Symyon** [comment]
@stiv-yakovenko 
`vcpkg install openblas:x64-windows`
