### ISSUE TITLE
Keeping multiple targets in vcpkg_installed

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#12525]
[specifications/manifests.md](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md) mentions that:
> `vcpkg install` without any port arguments will install the dependencies listed in the manifest file, and will remove any dependencies which are no longer in the dependency tree implied by the manifest file.

But this command also **removes the built files from _other_ targets/triplets**.

I'm using the same tree for Windows (`vcpkg_installed/x64-windows`) and linux (`vcpkg_installed/x64-linux`) through WSL and I want both to remain in that directory at the same time.

If this feature is not supposed to exist, then I don't see much point in vcpkg using `vcpkg_installed/<triplet>/` instead of `vcpkg_installed/` in the first place.

Any workarounds would also be appreciated.

Thanks for your time!

**Comment by NancyLi1013** [comment]
@strega-nil 
Could you please help take a look?
Thanks.

**Comment by strega-nil** [comment]
This is a bug; however, if you're using the CMake integration, you shouldn't have to worry about it.

**Comment by VelocityRa** [comment]
@strega-nil How so? I _am_ using CMake integration.
See the OP, I have the same tree for both windows and WSL.

**Comment by strega-nil** [comment]
You may have to update to the latest version of vcpkg; in the latest version, we put `vcpkg_installed` in the build directory.

**Comment by VelocityRa** [comment]
Yeah this was fixed, thanks!

**Comment by kartonrad** [comment]
I'm still facing this issue on 2025-12-05-d84fb805651077f4ed3a97b61fbad2b513462f8b

I am not using the manifest mode.
