### ISSUE TITLE
Error: Building package bzip2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by NinjaGo31** [microsoft/vcpkg#12615]
I'm trying to install libmysql:x64-windows, but every time I do it in the standard command prompt, I'm stuck in a loop with the following errors:

- error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown

- error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely

- error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown

- error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely

- error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown

- error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely

- error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))

- error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))

- error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

When I ran the same installation command in Git CMD, I got an error saying: 
Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

If anyone can help me with this, I'd appreciate it.

**Comment by JackBoosY** [comment]
This issue should be fixed,  please update vcpkg and rebuild bzip2. 

Thanks.

**Comment by fedapo** [comment]
I still have the problem:
`
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\faponte\AppData\Local\vcpkg\archives\54\547100163dd329fca01eca4a2cf079d390bed1a3.zip
-- Using cached C:/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\bzip2\msys-pacman-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)


Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
`
The error log is this.
`
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
`

**Comment by JackBoosY** [comment]
Please delete _VCPKG_PATH/downloads/tools/msys2_ and try again.

**Comment by fedapo** [comment]
_> Please delete _VCPKG_PATH/downloads/tools/msys2_ and try again._
It works. Thank you.
Does this mean that vcpkg uses an "embedded" msys2 (mingw) installation for building its libraries? Even if the system has Visual Studio installed?

**Comment by JackBoosY** [comment]
Yes,  it's build process requires msys2.
