### ISSUE TITLE
[Installing New Libary] Problem with detecting compiler hash for triplet

### ISSUE THREAD

**Issue by HoopDead** [microsoft/vcpkg#13890]
Hello guys, I'm dealing with pretty "serious" issue and I really don't know what's wrong? My attitude to the problem or the device that I'm working on.

System:

Windows 10.0.18362, x64 

Installation process gone well - running bootstrap-vcpkg and vcpkg integrate install commands won't show any errors logs

But when I'm trying to install new library, for example sqlite3 only this messages show up at my screen

```
PS C:\vcpkg> .\vcpkg.exe install sqlite3
Computing installation plan...
The following packages will be built and installed:
    sqlite3[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
PS C:\vcpkg>
```

Even if I try to install library for x64 based system it also won't install, and crashes at the same message

```
Computing installation plan...
The following packages will be built and installed:
    sqlite3[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
PS C:\vcpkg>
```

My triplets folder looks like that:

![Triplets folder](https://user-images.githubusercontent.com/26123401/95134676-918c9b80-0763-11eb-9cc1-1c57d10f86de.png)

**Comment by HoopDead** [comment]
I tried to update cmake to the newest version and running the installation with -- debug flag

![image](https://user-images.githubusercontent.com/26123401/95136511-84bd7700-0766-11eb-9190-f0404d7981f8.png)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you try to clone VCPKG to other disks and install library again?

**Comment by HoopDead** [comment]
Hello @LilyWangL, 
Thanks for your replay, I just have tried that after updating my Windows to the newest version. The problem remains, but for sure I am going to post code from my PowerShell.

I used command ``` .\vcpkg.exe install sqlite3 --debug"

On disc C:\

``` powershell

PS C:\Program Files (x86)\vcpkg> .\vcpkg.exe install sqlite3
Computing installation plan...
The following packages will be built and installed:
    sqlite3[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
PS C:\Program Files (x86)\vcpkg> .\vcpkg.exe install sqlite3 --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Using vcpkg-root: C:\Program Files (x86)\vcpkg
[DEBUG] Using installed-root: C:\Program Files (x86)\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\Program Files (x86)\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\Program Files (x86)\vcpkg\downloads
[DEBUG] Using packages-root: C:\Program Files (x86)\vcpkg\packages
[DEBUG] Using scripts-root: C:\Program Files (x86)\vcpkg\scripts
[DEBUG] Default binary cache path is: C:\Users\Mateusz\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin/cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    26036 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" "-DVCPKG_ROOT_DIR=C:/Program Files (x86)/vcpkg" "-DPACKAGES_DIR=C:/Program Files (x86)/vcpkg/packages" "-DBUILDTREES_DIR=C:/Program Files (x86)/vcpkg/buildtrees" "-D_VCPKG_INSTALLED_DIR=C:/Program Files (x86)/vcpkg/installed" "-DDOWNLOADS=C:/Program Files (x86)/vcpkg/downloads" -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Program Files (x86)\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    20188 us
The following packages will be built and installed:
    sqlite3[core]:x86-windows
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    21341 us
Detecting compiler hash for triplet x86-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd/git.exe
[DEBUG] CreateProcessW("C:\Program Files (x86)\vcpkg\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    16048 us
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64_x86   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)
[DEBUG] cmd_execute_and_stream_data() returned 1 after  1105003 us
[DEBUG] C:\Program Files (x86)\vcpkg\toolsrc\src\vcpkg\base\system.process.cpp(568)
[DEBUG] Exiting after 1218670 us (1202197 us)
PS C:\Program Files (x86)\vcpkg>

```

On disc D:\

PS D:\Programs\vcpkg> .\vcpkg.exe install sqlite3 --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Using vcpkg-root: D:\Programs\vcpkg
[DEBUG] Using installed-root: D:\Programs\vcpkg\installed
[DEBUG] Using buildtrees-root: D:\Programs\vcpkg\buildtrees
[DEBUG] Using downloads-root: D:\Programs\vcpkg\downloads
[DEBUG] Using packages-root: D:\Programs\vcpkg\packages
[DEBUG] Using scripts-root: D:\Programs\vcpkg\scripts
[DEBUG] Default binary cache path is: C:\Users\Mateusz\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin/cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    36115 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" -DVCPKG_ROOT_DIR=D:/Programs/vcpkg -DPACKAGES_DIR=D:/Programs/vcpkg/packages -DBUILDTREES_DIR=D:/Programs/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/Programs/vcpkg/installed -DDOWNLOADS=D:/Programs/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\Programs\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    25369 us
The following packages will be built and installed:
    sqlite3[core]:x86-windows
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    25054 us
Detecting compiler hash for triplet x86-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd/git.exe
[DEBUG] CreateProcessW("D:\Programs\vcpkg\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    18885 us
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64_x86   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)
[DEBUG] cmd_execute_and_stream_data() returned 1 after  1415800 us
[DEBUG] D:\Programs\vcpkg\toolsrc\src\vcpkg\base\system.process.cpp(568)
[DEBUG] Exiting after 1547872 us (1537461 us)
PS D:\Programs\vcpkg>

```

**Comment by LilyWangL** [comment]
Thanks for your reply. I can't found any error in this log. If you don't add `--debug`, could you install `sqlite3` successfully?

**Comment by BillyONeal** [comment]
Does "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" actually refer to a Visual Studio installation tree?

**Comment by JChatillon** [comment]
Exact same issue (with other packages).

**Comment by JChatillon** [comment]
> 
> 
> ...
> 

I tried to add a vcpkg.json manifest file, and open the project using Visual Studio (instead of generating a VS Solution using CMake...) and VS tried and fail too:
```
CMake generation started for default configuration: 'x64-Debug (default)'.
Found and using vcpkg toolchain file (C:/vcpkg/scripts/buildsystems/vcpkg.cmake).
Command line: "cmd.exe" /c ""c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Users\JChatillon\Documents\Dev\lst\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\Users\JChatillon\Documents\Dev\lst" 2>&1"
Working directory: D:\Users\JChatillon\Documents\Dev\lst\out\build\x64-Debug (default)
[CMake] -- Running vcpkg install
[CMake] CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:386 (message):
[CMake]   Running vcpkg install - failed
[CMake] Call Stack (most recent call first):
[CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93 (include)
[CMake]   CMakeLists.txt:2 (project)
[CMake] -- Configuring incomplete, errors occurred!
'cmd.exe' '/c ""c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Users\JChatillon\Documents\Dev\lst\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\Users\JChatillon\Documents\Dev\lst" 2>&1"' execution failed with error: ''cmd.exe' '/c ""c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Users\JChatillon\Documents\Dev\lst\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\Users\JChatillon\Documents\Dev\lst" 2>&1"' returned with exit code: 1'.
```

**Comment by JChatillon** [comment]
From my side, I solved the issue:
I had to clear the `HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun` registry entry which was trying to launch an old Anaconda batch file...

**Comment by BillyONeal** [comment]
@HoopDead Do you have something like that?

**Comment by HoopDead** [comment]
@BillyONeal I'm going to check it in a while because unfortunately, my computer decided to stop being my teammate and I had to buy a new disc. :)

**Comment by BillyONeal** [comment]
OK, considering of the 2 reporters here, 1 was caused by an autorun setting that tried to run a broken script, and the other was on a machine that experienced hardware failure, I'm closing this for now. If you experience similar problems, please open a new issue.

Thanks for the report!

**Comment by HoopDead** [comment]
Hey @BillyONeal @JChatillon!

I just put new disc into my computer and the problem happened again - but this time I tried to follow advice given by Jerome. Clearing the HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun (CURRENT USER, NOT LOCAL_MACHINE) and it is working! Thanks for your help.

**Comment by bela-mervado** [comment]
Yo

I had the same problem.. thanks
For me it was conemu, installed a while ago to have a console with ansi color escape codes.

thanks again
Béla

**Comment by Yourbee** [comment]
thanks, 
it fixed my vcpkg install and cmder problem for uninstalling conda.

**Comment by cramke** [comment]
> 
> 
> Hey @BillyONeal @JChatillon!
> 
> I just put new disc into my computer and the problem happened again - but this time I tried to follow advice given by Jerome. Clearing the HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun (CURRENT USER, NOT LOCAL_MACHINE) and it is working! Thanks for your help.

This worked for me, thanks! The issue was also related to anaconda.

**Comment by shelllet** [comment]
But Registry have no `Command Processor` in my computer,

**Comment by HoopDead** [comment]
Hey @shelllet do you have samee issue like us? Can you list your errors from terminal? Maybe we can figure something out :)

**Comment by dbalciunas** [comment]
Same problem here. I have "Command Processor" in HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER but there is no AutoRun value. I tried uninstalling and reinstalling vcpkg, CMake and Visual Studio. Installation in disk C gives the same result.

PS X:\Libraries\vcpkg> .\vcpkg.exe install eigen3:x64-windows
Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:x64-windows -> 3.3.9
Detecting compiler hash for triplet x64-windows...
PS X:\Libraries\vcpkg>

PS C:\vcpkg> .\vcpkg.exe install eigen3:x64-windows
Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:x64-windows -> 3.3.9
Detecting compiler hash for triplet x64-windows...
PS C:\vcpkg>

PS X:\Libraries\vcpkg> .\vcpkg.exe install eigen3:x64-windows --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: X:\Libraries\vcpkg
[DEBUG] Using installed-root: X:\Libraries\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: X:\Libraries\vcpkg\buildtrees
[DEBUG] Using downloads-root: X:\Libraries\vcpkg\downloads
[DEBUG] Using packages-root: X:\Libraries\vcpkg\packages
[DEBUG] Using scripts-root: X:\Libraries\vcpkg\scripts
[DEBUG] Using ports-root: X:\Libraries\vcpkg\ports
[DEBUG] Using versions-root: X:\Libraries\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\dbalc\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: D:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("D:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    28654 us
[DEBUG] CreateProcessW("D:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=X:/Libraries/vcpkg -DPACKAGES_DIR=X:/Libraries/vcpkg/packages -DBUILDTREES_DIR=X:/Libraries/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=X:/Libraries/vcpkg/installed -DDOWNLOADS=X:/Libraries/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "X:\Libraries\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    23484 us
The following packages will be built and installed:
    eigen3[core]:x64-windows -> 3.3.9
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    22588 us
Detecting compiler hash for triplet x64-windows...
[DEBUG] CreateProcessW("X:\Libraries\vcpkg\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    21343 us
[DEBUG] CreateProcessW("X:\Libraries\vcpkg\downloads\tools\powershell-core-7.1.0-windows\pwsh.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   229347 us
[DEBUG] CreateProcessW(cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] cmd_execute_and_stream_data() returned 255 after   684084 us
[DEBUG] C:\A\1\70\s\src\vcpkg\base\system.process.cpp(592)
[DEBUG] Exiting after 1048604 us (1039935 us)
PS X:\Libraries\vcpkg>

**Comment by shelllet** [comment]
> Hey @shelllet do you have samee issue like us? Can you list your errors from terminal? Maybe we can figure something out :)
```
PS C:\Users\admin> vcpkg.exe install eigen3:x64-windows --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\vcpkg
[DEBUG] Using installed-root: C:\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\vcpkg\downloads
[DEBUG] Using packages-root: C:\vcpkg\packages
[DEBUG] Using scripts-root: C:\vcpkg\scripts
[DEBUG] Using ports-root: C:\vcpkg\ports
[DEBUG] Using versions-root: C:\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\admin\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("C:\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    31965 us
[DEBUG] CreateProcessW("C:\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/vcpkg -DPACKAGES_DIR=C:/vcpkg/packages -DBUILDTREES_DIR=C:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed -DDOWNLOADS=C:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    16813 us
The following packages will be built and installed:
    eigen3[core]:x64-windows -> 3.3.9
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    21735 us
Detecting compiler hash for triplet x64-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    23171 us
[DEBUG] CreateProcessW("C:\vcpkg\downloads\tools\powershell-core-7.1.0-windows\pwsh.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   176453 us
[DEBUG] CreateProcessW(cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] cmd_execute_and_stream_data() returned 255 after   542080 us
[DEBUG] C:\A\1\70\s\src\vcpkg\base\system.process.cpp(592)
[DEBUG] Exiting after 895263 us (889344 us)
```

**Comment by barcharcraz** [comment]
VS 2019 preview 2 broke the -vcvars_ver parameter of vcvarsall.bat, causing this error. It's already been reported internally.

**Comment by dbalciunas** [comment]
Thanks a lot. Is there any workaround?

**Comment by barcharcraz** [comment]
not as far as I can tell. it should be fixed in the next VS 2019 preview release, however.

**Comment by MFMokbel** [comment]
@barcharcraz are you sure about this? I'm running Microsoft Visual Studio Enterprise 2019 Preview, Version 16.10.0 Preview 2.1, and still getting the same error!

**Comment by dbalciunas** [comment]
> @barcharcraz are you sure about this? I'm running Microsoft Visual Studio Enterprise 2019 Preview, Version 16.10.0 Preview 2.1, and still getting the same error!

I have 16.10.0 Preview 2.1 too and the problem persists. I have problems running nvcc (cuda compiler) and qt. 

vcvarsall.bat gives an error no matter what parameters you pass. I cannot understand how this is not causing more people to complaint.  It seems not to bother Microsoft a lot.

**Comment by bjude** [comment]
As a workaround while vcvarsall.bat gets fixed in the next preview, comment out the `vcvars_option =`  lines [here](https://github.com/microsoft/vcpkg-tool/blob/9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg/visualstudio.cpp#L253-L262) and recompile vcpkg.

Note that the source has been split out into a separate repo so you'll need to build that and copy the executable over into your vcpkg directory

**Comment by dbalciunas** [comment]
> As a workaround while vcvarsall.bat gets fixed in the next preview, comment out the `vcvars_option =` lines [here](https://github.com/microsoft/vcpkg-tool/blob/9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg/visualstudio.cpp#L253-L262) and recompile vcpkg.
> 
> Note that the source has been split out into a separate repo so you'll need to build that and copy the executable over into your vcpkg directory

Thanks, I`m going to try. In the meantime I was downgraded to VS Community 16.9.4.

**Comment by barcharcraz** [comment]
it works in preview 3.0 (sorry, when I posted my comment the bug was prioritized but not quite fixed yet, and preview 2.1 came faster than I expected).

**Comment by ErickGatica** [comment]
Hi guys, I solved it adding --triplet x64-windows , now i can install the libraries, I had the same error
