### ISSUE TITLE
[ffmpeg] build failure

### ISSUE THREAD

**Issue by MarekMaslanka** [microsoft/vcpkg#14094]
**Host Environment**
- OS: Windows
- CI: Github actions

**To Reproduce**
`vcpkg install ffmpeg`

**Failure logs** 
```
-- Installing: C:/vcpkg/downloads/tools/yasm/1.3.0.6/yasm.exe
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/coreutils-8.32-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/grep-3.0-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/sed-4.8-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libpcre-8.44-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/gawk-5.1.0-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/mpfr-4.1.0-1-x86_64.pkg.tar.zst...
-- Downloading https://repo.msys2.org/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libreadline-8.0.004-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/ncurses-6.2-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/pkg-config-0.29.2-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/make-4.3-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libintl-0.19.8.1-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
```

**Additional context**
Building ffmpeg using Github actions CI with simple yaml:
```
name: Build ffmpeg
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: ffmpeg
        run: vcpkg install ffmpeg
```

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue ha been fixed in PR #13889. Now when the primary source is down, VCPKG will download from `msys2-mirror`, like this:
```
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/gcc-libs-9.3.0-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/msys2-runtime-3.1.6-3-x86_64.pkg.tar.xz...
-- Using msys root at E:/1019/vcpkg/downloads/tools/msys2/8f86d90f10246c56
```

**Comment by turska79** [comment]
What is the status of this? As also running vcpkg install vcpkg-gfortran:x64-windows produces 
Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"

Reason being that  https://repo.msys2.org doenst contain version 1.16-1. It has only version 1.16-2.

**Comment by sfhacker** [comment]
Are we STILL having issues building ffmpeg?
I thought all the reported issues had been fixed!

@MarekMaslanka I suspect your environment is broken!

**Comment by MarekMaslanka** [comment]
@sfhacker After manually update vcpkg in github actions environment ffmpeg is building successful

**Comment by turska79** [comment]
Ah sorry. Building gfortran and not ffmpeg. I shall open a new ticket? As didn't notice anything related to that
