### ISSUE TITLE
Different triplets appear to conflict

### ISSUE THREAD

**Issue by mcgoo** [microsoft/vcpkg#14956]
A custom triplet on Linux seems to conflict with the default linux triplet, resulting in a build failure. It occurs with at least `brotli` and `bzip2` so I think it is not package specific. Installing `bzip2:x64-linux` and then `bzip2:test-triplet` results in an error message that mentions `x64-linux` during the `test-triplet` build.

~~Doing the same thing on macOS (x64-osx->test-triplet) seems to work fine.~~ The same issue occurs on macOS.

**Environment**
- OS: Ubuntu 20.04
- Compiler: GCC 9.3

**To Reproduce**
In a clean vcpkg tree:
1. `cp triplets/x64-linux.cmake triplets/test-triplet.cmake`
2. `./vcpkg install bzip2:x64-linux bzip2:test-triplet`

**Expected behavior**

Package `bzip2:test-triplet` should build.

**Failure logs** 
```
ubuntu@primary ~/t/vcpkg (master)> cp triplets/x64-linux.cmake triplets/test-triplet.cmake
ubuntu@primary ~/t/vcpkg (master)> ./vcpkg install bzip2:x64-linux bzip2:test-triplet
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:test-triplet -> 1.0.8#1
    bzip2[core]:x64-linux -> 1.0.8#1
Detecting compiler hash for triplet test-triplet...
Detecting compiler hash for triplet x64-linux...
Using cached binary package: /home/ubuntu/.cache/vcpkg/archives/0f/0fee4c5435b6640cf089306114c128a898c90da3.zip
Using cached binary package: /home/ubuntu/.cache/vcpkg/archives/0f/0fee4c5435b6640cf089306114c128a898c90da3.zip
Starting package 1/2: bzip2:test-triplet
Building package bzip2[core]:test-triplet...
Building package bzip2[core]:test-triplet... done
Installing package bzip2[core]:test-triplet...
Installing package bzip2[core]:test-triplet... done
Elapsed time for package bzip2:test-triplet: 1.385 ms
Starting package 2/2: bzip2:x64-linux
Building package bzip2[core]:x64-linux...
Building package bzip2[core]:x64-linux... done
Installing package bzip2[core]:x64-linux...
The following files are already installed in /home/ubuntu/tmp/vcpkg/installed/x64-linux and are in conflict with bzip2:x64-linux

Installed by bzip2:x64-linux
    debug/lib/libbz2d.a
    debug/lib/pkgconfig/bzip2.pc
    include/bzlib.h
    lib/libbz2.a
    lib/pkgconfig/bzip2.pc
    share/bzip2/copyright
    share/bzip2/usage
    share/bzip2/vcpkg_abi_info.txt
    tools/bzip2/bzip2
    tools/bzip2/bzip2recover

Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-linux
  Vcpkg version: 2020.11.12-unknownhash
```

**Comment by PhoebeHui** [comment]
@mcgoo, thanks for reporting this issue!

This should be a vcpkg bug, also repored on windows platform. @BillyONeal, could you please have a look?

**Comment by BillyONeal** [comment]
```
billy@bion-ubuntu-18-04:~/vcpkg$ cp triplets/x64-linux.cmake triplets/test-triplet.cmake
billy@bion-ubuntu-18-04:~/vcpkg$ ./vcpkg install bzip^C
billy@bion-ubuntu-18-04:~/vcpkg$ ./vcpkg install bzip2:x64-linux bzip2:test-triplet
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:test-triplet -> 1.0.8#1
    bzip2[core]:x64-linux -> 1.0.8#1
Detecting compiler hash for triplet test-triplet...
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/billy/.cache/vcpkg/archives/28/28c2f67d62f0003346a8e7c94dee02c2b852c12c.zip
Could not locate cached archive: /home/billy/.cache/vcpkg/archives/28/28c2f67d62f0003346a8e7c94dee02c2b852c12c.zip
Starting package 1/2: bzip2:test-triplet
Building package bzip2[core]:test-triplet...
-- Fetching https://sourceware.org/git/bzip2.git...
-- Extracting source /home/billy/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at /home/billy/vcpkg/buildtrees/bzip2/src/8689526147-d8c5a1c4b4.clean
-- Configuring test-triplet-dbg
-- Configuring test-triplet-rel
-- Building test-triplet-dbg
-- Building test-triplet-rel
-- Fixing pkgconfig file: /home/billy/vcpkg/packages/bzip2_test-triplet/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: /home/billy/vcpkg/packages/bzip2_test-triplet/debug/lib/pkgconfig/bzip2.pc
-- Installing: /home/billy/vcpkg/packages/bzip2_test-triplet/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/billy/.cache/vcpkg/archives/28/28c2f67d62f0003346a8e7c94dee02c2b852c12c.zip
Building package bzip2[core]:test-triplet... done
Installing package bzip2[core]:test-triplet...
Installing package bzip2[core]:test-triplet... done
Elapsed time for package bzip2:test-triplet: 2.297 s
Starting package 2/2: bzip2:x64-linux
Building package bzip2[core]:x64-linux...
-- Using cached /home/billy/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at /home/billy/vcpkg/buildtrees/bzip2/src/8689526147-d8c5a1c4b4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/billy/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at /home/billy/vcpkg/buildtrees/bzip2/src/8689526147-d8c5a1c4b4.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/billy/vcpkg/packages/bzip2_x64-linux/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: /home/billy/vcpkg/packages/bzip2_x64-linux/debug/lib/pkgconfig/bzip2.pc
-- Installing: /home/billy/vcpkg/packages/bzip2_x64-linux/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/billy/.cache/vcpkg/archives/28/28c2f67d62f0003346a8e7c94dee02c2b852c12c.zip
Building package bzip2[core]:x64-linux... done
Installing package bzip2[core]:x64-linux...
Installing package bzip2[core]:x64-linux... done
Elapsed time for package bzip2:x64-linux: 1.011 s

Total elapsed time: 3.761 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)

billy@bion-ubuntu-18-04:~/vcpkg$
```

hmmmm; @mcgoo can you report the results of `git rev-parse HEAD`?

**Comment by BillyONeal** [comment]
(In my output above I was at c303dd024e2dc03a0665ddffbb12a1077933e649 )

**Comment by mcgoo** [comment]
It was in de70813cf3. I just checked 066c6fd7 which is this instant's master. Tested on macOS, still fails.

The only difference was that I ran the installs in two steps.  I `rm`'d the  tree because in the past I had only been running `git clean -fdx`, but it makes no difference.
```
rm -rf vcpkg
git clone https://github.com/microsoft/vcpkg
cd vcpkg
./bootstrap-vcpkg.sh -allowAppleClang
cp triplets/x64-osx.cmake triplets/test-triplet.cmake
./vcpkg install bzip2
./vcpkg install bzip2:test-triplet
```

**Comment by mcgoo** [comment]
Looks like it's been around for a while. (I never hit it on my own machine, only on a CI build stepping through lots of configurations.)

```
52a9d9a9e481f835e9c3b9ba028ff2f833cb3624 is the first bad commit
commit 52a9d9a9e481f835e9c3b9ba028ff2f833cb3624
Author: ras0219 <533828+ras0219@users.noreply.github.com>
Date:   Mon Jul 13 12:03:53 2020 -0700

    [vcpkg] Enable binary caching by default (#12370)

    * [vcpkg] Enable binary caching by default. Support `x-` migration.

    Fix passing multiple copies of single parameter arguments.

    * [vcpkg] Handle x- prefixes for general arguments

    * [vcpkg] Fix #12285 and improve documentation of default binary cache path

    * [vcpkg] Revert x- prefix homogenization for per-command arguments

    * [vcpkg] Only use accelerated compiler detection for Windows Desktop + Ninja. Improve breadcrumbs for users encountering issues.

    * [vcpkg] Fix compiler tracking not pre-downloading Ninja. Fix compiler tracking not looking in -err.log.

    * [vcpkg] Update toolsrc/src/vcpkg/binarycaching.cpp

    Co-authored-by: Billy O'Neal <bion@microsoft.com>

    * [vcpkg] Format

    Co-authored-by: Robert Schumacher <roschuma@microsoft.com>
    Co-authored-by: Billy O'Neal <bion@microsoft.com>

 scripts/detect_compiler/CMakeLists.txt    | 14 ++++---
 scripts/detect_compiler/portfile.cmake    |  4 +-
 toolsrc/include/vcpkg/vcpkgcmdarguments.h |  6 +--
 toolsrc/src/vcpkg/base/system.cpp         | 15 ++++++-
 toolsrc/src/vcpkg/binarycaching.cpp       | 66 +++++++++++++++++++------------
 toolsrc/src/vcpkg/build.cpp               | 13 ++++++
 toolsrc/src/vcpkg/vcpkgcmdarguments.cpp   | 32 +++++++++++++--
 7 files changed, 109 insertions(+), 41 deletions(-)
bisect run success
```

**Comment by BillyONeal** [comment]
Right, it would make sense that the binary caching change would have broken it since that added cross-triplet actions to consider as part of binary caching, but it doesn't repro for me at all :(

**Comment by mcgoo** [comment]
Weird. To confirm, --no-binarycaching does fix it for me.

**Comment by PhoebeHui** [comment]
I think the binary cache cause this issue, @BillyONeal, here is repro steps:

```
./vcpkg install bzip2:x64-linux
./vcpkg install bzip2:test-triplet
```

```

PS F:\vcpkg\clean> ./vcpkg install bzip2
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows -> 1.0.8#1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
-- Using cached F:/VCPKG/clean/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at F:/VCPKG/clean/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/VCPKG/clean/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at F:/VCPKG/clean/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at F:/VCPKG/clean/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/VCPKG/clean/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: F:/VCPKG/clean/packages/bzip2_x86-windows/debug/lib/pkgconfig/bzip2.pc
-- Installing: F:/VCPKG/clean/packages/bzip2_x86-windows/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Building package bzip2[core]:x86-windows... done
Installing package bzip2[core]:x86-windows...
Installing package bzip2[core]:x86-windows... done
Elapsed time for package bzip2:x86-windows: 9.509 s

Total elapsed time: 13.79 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)

PS F:\vcpkg\clean> ./vcpkg install bzip2:test-triplet
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:test-triplet -> 1.0.8#1
Detecting compiler hash for triplet test-triplet...
Using cached binary package: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Starting package 1/1: bzip2:test-triplet
Building package bzip2[core]:test-triplet...
Building package bzip2[core]:test-triplet... done
Installing package bzip2[core]:test-triplet...
The following files are already installed in F:/VCPKG/clean/installed/x86-windows and are in conflict with bzip2:x86-windows

Installed by bzip2:x86-windows
    bin/bz2.dll
    bin/bz2.pdb
    debug/bin/bz2d.dll
    debug/bin/bz2d.pdb
    debug/lib/bz2d.lib
    debug/lib/pkgconfig/bzip2.pc
    include/bzlib.h
    lib/bz2.lib
    lib/pkgconfig/bzip2.pc
    share/bzip2/copyright
    share/bzip2/usage
    share/bzip2/vcpkg_abi_info.txt
    tools/bzip2/bzip2.exe
    tools/bzip2/bzip2recover.exe

Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:test-triplet
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
PS F:\vcpkg\clean> git rev-parse HEAD
c303dd024e2dc03a0665ddffbb12a1077933e649
```

**Comment by PhoebeHui** [comment]
If I run ./vcpkg install bzip2 bzip2:test-triplet, it will not repro this issue, it seems the binary cache not used in this way.

```
PS F:\vcpkg\clean> ./vcpkg install bzip2 bzip2:test-triplet
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:test-triplet -> 1.0.8#1
    bzip2[core]:x86-windows -> 1.0.8#1
Detecting compiler hash for triplet test-triplet...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Starting package 1/2: bzip2:test-triplet
Building package bzip2[core]:test-triplet...
-- Using cached F:/VCPKG/clean/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at F:/VCPKG/clean/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/VCPKG/clean/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at F:/VCPKG/clean/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring test-triplet
-- Building test-triplet-dbg
-- Building test-triplet-rel
-- Using msys root at F:/VCPKG/clean/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/VCPKG/clean/packages/bzip2_test-triplet/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: F:/VCPKG/clean/packages/bzip2_test-triplet/debug/lib/pkgconfig/bzip2.pc
-- Installing: F:/VCPKG/clean/packages/bzip2_test-triplet/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Building package bzip2[core]:test-triplet... done
Installing package bzip2[core]:test-triplet...
Installing package bzip2[core]:test-triplet... done
Elapsed time for package bzip2:test-triplet: 8.327 s
Starting package 2/2: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
-- Using cached F:/VCPKG/clean/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at F:/VCPKG/clean/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/VCPKG/clean/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at F:/VCPKG/clean/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at F:/VCPKG/clean/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/VCPKG/clean/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: F:/VCPKG/clean/packages/bzip2_x86-windows/debug/lib/pkgconfig/bzip2.pc
-- Installing: F:/VCPKG/clean/packages/bzip2_x86-windows/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\10\10824a657fc4338b0c85c1486bdc30f1076b9e7d.zip
Building package bzip2[core]:x86-windows... done
Installing package bzip2[core]:x86-windows...
Installing package bzip2[core]:x86-windows... done
Elapsed time for package bzip2:x86-windows: 7.799 s

Total elapsed time: 21.83 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)
```

**Comment by JackBoosY** [comment]
This issue was fixed in the master branch.

**Comment by kreuzerkrieg** [comment]
I think the issue is back.
Added a custom triplet and toolchain to build with clang and now I see in the CLion the following output

> /snap/clion/248/bin/cmake/linux/x64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/snap/clion/248/bin/ninja/linux/x64/ninja -DCMAKE_C_COMPILER=/usr/bin/clang-16 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 -DCMAKE_INSTALL_PREFIX=./install -DENABLE_TESTS=ON -DUSE_GTEST=ON -DVCPKG_TARGET_TRIPLET=x64-linux-clang16 -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/user/.clion-vcpkg/vcpkg/scripts/toolchains/linux-clang16.cmake -DCMAKE_TOOLCHAIN_FILE=/home/user/.clion-vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -S /home/user/Development/project -B /home/user/Development/project/cmake-build-debug-clang16
> -- Running vcpkg install
> Loading dependency information for 113 packages...
> Detecting compiler hash for triplet x64-linux...
> Detecting compiler hash for triplet x64-linux-clang16...
> 
and it created some of the packages for `x64-linux` triplet and some for `x64-linux-clang16`
@JackBoosY should this issue be reopened or should I open another one?

**Comment by JackBoosY** [comment]
@kreuzerkrieg Please open a new issue.

**Comment by kreuzerkrieg** [comment]
[Done](https://github.com/microsoft/vcpkg/issues/33040)
