### ISSUE TITLE
[pcl] Visualization headers are not installed

### ISSUE THREAD

**Issue by JorgeRomeoInfaimon** [microsoft/vcpkg#15130]
When pcl libraries are installed, I am trying to compile some samples found in the tutorials, but I cannot compile because the pcl/visualization headers cannot be found.

They do not exist in vcpkg/installed/include directory. Maybe they should be installed and the required components compiled.

**Comment by JackBoosY** [comment]
I think if we need to use the feature `visualization`, we should enable the feature vtk first.
Will check later.

**Comment by JackBoosY** [comment]
```
-- The following subsystems will not be built:
--   visualization: VTK was not found.
```

**Comment by JackBoosY** [comment]
```
CMake Deprecation Warning at F:/vcpkg/installed/x86-windows/share/vtk/vtk-config.cmake:64 (message):
  The new name for the 'vtkChartsCore' component is 'ChartsCore'
Call Stack (most recent call first):
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package)
  CMakeLists.txt:394 (find_package)


CMake Deprecation Warning at F:/vcpkg/installed/x86-windows/share/vtk/vtk-config.cmake:64 (message):
  The new name for the 'vtkCommonCore' component is 'CommonCore'
Call Stack (most recent call first):
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package)
  CMakeLists.txt:394 (find_package)
...
CMake Warning at F:/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package):
  Found package configuration file:

    F:/vcpkg/installed/x86-windows/share/vtk/vtk-config.cmake

  but it set VTK_FOUND to FALSE so package "VTK" is considered to be NOT
  FOUND.  Reason given by package:

  Could not find the VTK package with the following required components:
  RenderingContextOpenGL.
```
After searching for this issue from upstream(https://github.com/PointCloudLibrary/pcl/issues/4412), I found that pcl does not support VTK 9.0 in our master branch now.
Waiting for upstream fix this issue(https://github.com/PointCloudLibrary/pcl/pull/4262).

**Comment by VXallset** [comment]
Any update pls?

**Comment by JackBoosY** [comment]
@VXallset Waiting for [official fix](https://github.com/PointCloudLibrary/pcl/pull/4262).

**Comment by HelliceSaouli** [comment]
What should we do can we use some old version ?

**Comment by JackBoosY** [comment]
https://github.com/PointCloudLibrary/pcl/pull/4262 was merged, I will handle this issue in the nearly future.

**Comment by JackBoosY** [comment]
Since the changes is huge, I think we should wait for the next release of pcl.

**Comment by JorgeRomeoInfaimon** [comment]
Understood. Thanks for your hard work!

**Comment by tungts1101** [comment]
As missing the visualizer header is quite cumbersome in visualizing data, should you recommend a proper way to install an older version of PCL with vcpkg?

**Comment by JackBoosY** [comment]
We should update to 1.11.1.

**Comment by JackBoosY** [comment]
Hi guys, since pcl was updated to 1.11.1 in vcpkg, is this issue resolved?

**Comment by HelliceSaouli** [comment]
@JackBoosY still the same issue

**Comment by JackBoosY** [comment]
The version 1.11.1 doesn't include the changes, waiting for 1.11.2 release.

**Comment by HelliceSaouli** [comment]
1.12.0 is out you guys any news here .??

**Comment by JonLiu1993** [comment]
@HelliceSaouli ,Currently pcl1.12.0 is released as a pre-release version. Users may have problems when using it. It will be updated after the official version is released according to our policy.

**Comment by raahilsha-z** [comment]
PCL just pushed their release a couple hours ago, and I've opened a pull request here with those changes:

https://github.com/microsoft/vcpkg/pull/18855

**Comment by HelliceSaouli** [comment]
EPIC, Thank you guys

**Comment by YhQIAO** [comment]
Is this issue fixed in 2021.9?

**Comment by JackBoosY** [comment]
@YhQIAO See https://github.com/microsoft/vcpkg/pull/18855#issuecomment-922207871.

**Comment by JackBoosY** [comment]
I confirmed this feature is still not added, I will open a PR to add it.
