### ISSUE TITLE
Unable to install openssl

### ISSUE THREAD

**Issue by newmanlai** [microsoft/vcpkg#15223]
**Describe the bug**
When running the command below, it fails to build the openssl[core]:x86-windows package
`cmd.exe /c d:\w\c\35\s\vcpkg.exe install openssl`

We tried building it on Dec. 9, 2020 and it was all fine. But on Dec. 17, 2020, it started to fail even on different environment. 

**Environment**
- OS: Windows Server 2012 R2 Standard, Windows 10 Enterprise LTSC
- Vcpkg version: 2020.11.12-nohash

**To Reproduce**
1. ./vcpkg install openssl
2. See error
Building package openssl[core]:x86-windows...
-- Downloading https://www.openssl.org/source/openssl-1.1.1h.tar.gz...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 22;"HTTP response code said error"
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 16;"Error in the HTTP2 framing layer"

**Expected behavior**
It is expected to succeed without errors. Here is an example of the successful build:
[install_openssl_succeeded_log.txt](https://github.com/microsoft/vcpkg/files/5720156/install_openssl_succeeded_log.txt)

**Failure logs** 
[install_openssl_error_log.txt](https://github.com/microsoft/vcpkg/files/5720151/install_openssl_error_log.txt)

**Additional context**
I tried going to https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip directly from the browser and see the "Raptor not found" page.
When I tried http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip directly from the browser, it can download the zip without problems.

**Comment by iko1** [comment]
I got the same error on OS(Windows Server 2012 R2) and Vcpkg(2020.11.12-nohash):
```
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.
0.1-32bit.zip... Failed. Status: 16;"Error in the HTTP2 framing layer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

```

**Comment by ckaminski** [comment]
@iko1 where did you get your perl from?  The link vcpkg is using is broken, and when I use the following link, vcpkg doesn't seem to extract it properly.  
http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip


`-- Using cached D:/repos/cpp/vcpkg/downloads/openssl-1.1.1h.tar.gz
-- Using cached D:/repos/cpp/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/repos/cpp/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:593 (message):
  Unable to find PERL
Call Stack (most recent call first):
  ports/openssl/portfile.cmake:12 (vcpkg_find_acquire_program)
  scripts/ports.cmake:136 (include)


Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
PS D:\repos\cpp\vcpkg> dir .\downloads\tools\perl\5.30.0.1\                 `

**Comment by iko1** [comment]
@ckaminski, the filename looks familiar, what about the hash? 
SHA256: eb296d3f1ad1bcc2023f1317ed1969aed4c74cc57c1341784705653512e8c5a5
Or your "D drive" is formatted with FAT32 filesystem? if so please try to do the same procedure on NTFS volume.

**Comment by ckaminski** [comment]
Thank you @iko1, I stumbled across the exFat issue early this morning!   converting the filesystem to ntfs cured the issue.

**Comment by NancyLi1013** [comment]
@newmanlai 

Thanks for posting this issue.

It might be something with your local network. 

Please download it manually and put it in _vcpkg_root_path/downloads/tools_ folder to rebuild `openssl`.

@ckaminski 

The extract issue you mentioned above is related with your local environment. Seems you have solved the problem with the help of @iko1.

```
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/repos/cpp/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:593 (message):
```

**Comment by ckaminski** [comment]
Downloading the link directly from the strawberryperl site worked ok.  The version vcpkg attempts to download returns a 404.  

https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip 

^^ as of this writing this link is apparently no longer valid. 

I have the same issue as @newmanlai.

**Comment by NancyLi1013** [comment]
@ckaminski 

Thanks for your clarification about this.

vcpkg provides two URLs to get `perl`. The one you mentioned seems broken, but another one is normal. 

vcpkg will try to download `perl` via these two link addresses.

Please see here:
https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake#L74_L77

This can be proved with the following build process:

```
PS F:\test\vcpkg> .\vcpkg.exe install openssl
Computing installation plan...
A suitable version of cmake was not found (required v3.18.4). Downloading portable cmake v3.18.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-win32-x86.zip -> F:\test\vcpkg\downloads\cmake-3.18.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> F:\test\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> F:\test\vcpkg\downloads\22ea847d-nuget.exe
The following packages will be built and installed:
    openssl[core]:x86-windows -> 1.1.1h#4
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- Downloading https://www.openssl.org/source/openssl-1.1.1h.tar.gz...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 22;"HTTP response code said error"
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Cleaning sources at F:/test/vcpkg/buildtrees/openssl/src/openssl-1-09fb822c56.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test/vcpkg/downloads/openssl-1.1.1h.tar.gz
-- Using source at F:/test/vcpkg/buildtrees/openssl/src/openssl-1-09fb822c56.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip...
-- Downloading https://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: F:/test/vcpkg/packages/openssl_x86-windows/share/openssl/copyright
-- Installing: F:/test/vcpkg/packages/openssl_x86-windows/share/openssl/usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x86-windows... done
Installing package openssl[core]:x86-windows...
Installing package openssl[core]:x86-windows... done
Elapsed time for package openssl:x86-windows: 7.24 min

Total elapsed time: 7.377 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
```

**Comment by newmanlai** [comment]
@NancyLi1013 

Thank you for looking into the issue. As a workaround, we have to download perl zip file manually from the second link (http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip) and copy it to vcpkg_root_path/downloads in order to build openssl.

**Comment by NancyLi1013** [comment]
Thanks all for the focus on this issue.

I'm closing this issue for now since it has been solved.

**Comment by dbierek** [comment]
Can we reopen this? It's definitely still an issue. Trying to install `openssl` with a fresh vcpkg on an exFAT drive fails with this exact error. I don't think the solution should be to force users to reformat their drives for one dependency, when other dependencies work fine.
```
Installing 8/23 openssl:x64-windows@3.3.1#1...
Building openssl:x64-windows@3.3.1#1...
C:\Users\danny\AppData\Local\vcpkg\registries\git-trees\038ce0eca1d7e3f285a8de86c75bb8b89255994d: info: installing overlay port from here
Downloading https://github.com/openssl/openssl/archive/openssl-3.3.1.tar.gz -> openssl-openssl-openssl-3.3.1.tar.gz
Successfully downloaded openssl-openssl-openssl-3.3.1.tar.gz
-- Extracting source D:/workspace/NavKit/extern/vcpkg/downloads/openssl-openssl-openssl-3.3.1.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch asm-armcap.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at D:/workspace/NavKit/extern/vcpkg/buildtrees/openssl/src/nssl-3.3.1-1ae1909b44.clean
Downloading https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip -> strawberry-perl-5.40.0.1-64bit-portable.zip
Successfully downloaded strawberry-perl-5.40.0.1-64bit-portable.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/workspace/NavKit/extern/vcpkg/downloads/strawberry-perl-5.40.0.1-64bit-portable.zip
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:231 (message):
  Unable to find PERL
Call Stack (most recent call first):
  C:/Users/danny/AppData/Local/vcpkg/registries/git-trees/038ce0eca1d7e3f285a8de86c75bb8b89255994d/windows/portfile.cmake:6 (vcpkg_find_acquire_program)
  C:/Users/danny/AppData/Local/vcpkg/registries/git-trees/038ce0eca1d7e3f285a8de86c75bb8b89255994d/portfile.cmake:69 (include)
  scripts/ports.cmake:196 (include)


error: building openssl:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle openssl:x64-windows: 42 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error+on+x64-windows&body=Copy%20issue%20body%20from%20D%3A%2Fworkspace%2FNavKit%2Fbuild%2Fx64-debug%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  "C:\Program Files\GitHub CLI\gh.exe" issue create -R microsoft/vcpkg --title "[openssl] Build failure on x64-windows" --body-file D:/workspace/NavKit/build/x64-debug/vcpkg_installed/vcpkg/issue_body.md
Completed submission of vcpkg-cmake-get-vars:x64-windows to 1 binary cache(s) in 30.5 ms
-- Running vcpkg install - failed
CMake Error at extern/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (message):
  vcpkg install failed.  See logs for more information:
  D:\workspace\NavKit\build\x64-debug\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Users/danny/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:14 (project)
```

**Comment by miguelmartins1987** [comment]
Possible workaround? It seems that manually extracting the contents of %VCPKG_HOME%\downloads\strawberry-perl-5.42.0.1-64bit-portable.zip to %VCPKG_HOME%\downloads\tools\perl\5.42.0.1 with 7-zip gets us past the "Unable to find PERL" issue.

It then downloads JOM, and complains that it is "Unable to find JOM". Same thing: extracting the contents of %VCPKG_HOME%\downloads\jom_1_1_4.zip to %VCPKG_HOME%\downloads\tools\jom\jom-1_1_4 gets us past that.

I believe the real "culprit" here on exFAT drives is "CMake version 3.31.6-msvc6" which, to date, ships with the latest Build Tools for Visual Studio 2022 (and likely also ships with the latest Visual Studio 2022 itself), but I'm not 100% sure.

Either way, these steps seem to work, even on exFAT drives. They worked for me, at least... I'm uncertain if they'll work for everybody else.

Oh, and be sure to replace %VCPKG_HOME% with your actual vcpkg root directory. Also, if it matters, the version of OpenSSL I managed to install is 3.1.3.

**EDIT:** This also works with the latest version of OpenSSL to date (3.6.0). Also, using the latest version of CMake to date (4.2.0) to extract %VCPKG_HOME%\downloads\strawberry-perl-5.42.0.1-64bit-portable.zip (`cmake -E tar x strawberry-perl-5.42.0.1-64bit-portable.zip`) yields the same **archive_write_finish_entry()** error... So, despite what I initially said about "CMake version 3.31.6-msvc6" being the culprit, it seems that's not the case. Again, take this with a grain of salt, but I now believe the real "culprit" is the version of libarchive that CMake uses.
