### ISSUE TITLE
[tensorflow[*]:x64-windows] build failure

### ISSUE THREAD

**Issue by kuelite** [microsoft/vcpkg#15542]
**Host Environment**
- OS: Windows10
- Compiler: revision

**To Reproduce**
.\vcpkg install  tensorflow[*]:x64-windows

**Failure logs** 

PS C:\Users\mmd> cd I:\src\vcpkg
PS I:\src\vcpkg> .\vcpkg install  tensorflow[*]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    tensorflow[core]:x64-windows -> 2.3.1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\mmd\AppData\Local\vcpkg\archives\c8\c8aefe826d775ca4566c1699efad6683737daba0.zip
Starting package 1/1: tensorflow:x64-windows
Building package tensorflow[core]:x64-windows...
-- Using msys root at I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b
-- Using cached I:/src/vcpkg/downloads/tensorflow-tensorflow-v2.3.1.tar.gz
-- Applying patch ../tensorflow-common/fix-build-error.patch
-- Applying patch ../tensorflow-common/fix-dbg-build-errors.patch
-- Applying patch ../tensorflow-common/fix-more-build-errors.patch
-- Using source at I:/src/vcpkg/buildtrees/tensorflow/src/v2.3.1-3bb65f15d0.clean
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/usr/bin/bash.exe --noprofile --norc -c "'I:/src/vcpkg/downloads/tools/bazel/3.7.0-windows/bazel.exe' build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      I:\src\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  ports/tensorflow-common/tensorflow-common.cmake:219 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:136 (include)

Error: Building package tensorflow:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**

$TEST_TMPDIR defined: output root default is 'i:\src\vcpkg\buildtrees\.bzl' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/lib/python3.8/site-packages --python_path=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python3.exe --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define framework_shared_object=false
Loading: 
Loading: 0 packages loaded
Analyzing: 2 targets (1 packages loaded)
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
Analyzing: 2 targets (66 packages loaded, 161 targets configured)
WARNING: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/core/BUILD:1749:11: in linkstatic attribute of cc_library rule //tensorflow/core:lib_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
Analyzing: 2 targets (135 packages loaded, 7697 targets configured)
WARNING: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/core/BUILD:2161:16: in linkstatic attribute of cc_library rule //tensorflow/core:framework_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
INFO: Repository aws instantiated at:
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:19:16: in <toplevel>
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace.bzl:108:27: in tf_repositories
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace.bzl:49:8: in initialize_third_party
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/aws/workspace.bzl:9:29: in repo
Repository rule third_party_http_archive defined at:
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:219:43: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class java.io.IOException Tried to reconnect at offset 1,336,497 but server didn't support it
ERROR: An error occurred during the fetch of repository 'aws':
   Traceback (most recent call last):
	File "I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl", line 188, column 33, in _third_party_http_archive
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz, https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz] to I:/src/vcpkg/buildtrees/.bzl/_bazel_mmd/gedkvm5a/external/aws/temp829777694932992011/1.7.336.tar.gz: Tried to reconnect at offset 1,336,497 but server didn't support it
ERROR: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/core/platform/s3/BUILD:76:11: //tensorflow/core/platform/s3:s3_file_system depends on @aws//:aws in repository @aws which failed to fetch. no such package '@aws//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz, https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz] to I:/src/vcpkg/buildtrees/.bzl/_bazel_mmd/gedkvm5a/external/aws/temp829777694932992011/1.7.336.tar.gz: Tried to reconnect at offset 1,336,497 but server didn't support it
ERROR: Analysis of target '//tensorflow:tensorflow.dll' failed; build aborted: Analysis failed
INFO: Elapsed time: 133.026s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (174 packages loaded, 11226 targets configured)
FAILED: Build did NOT complete successfully (174 packages loaded, 11226 targets configured)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
So i know whats wrong with it,  vcpkg cannot dowload 1.7.336.tar.gz using the links 
[https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz, 
https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz] 
so i download the file 1.7.336.tar.gz  using other tools,  but how can  i do to make vcpkg continue to compile?

Thanks in advance.

**Comment by NancyLi1013** [comment]
Hi @kuelite 

It seems this issue has been solved in recent commits. I cannot reproduce this on my machine now.

Could you please try to update vcpkg to the latest version to rebuild this port?

Thanks.

**Comment by kuelite** [comment]
i used git pull to update vcpkg and rebuild this port, but...still doesnt work.

PS I:\src\vcpkg> .\vcpkg version
Vcpkg package management program version 2020.11.12--unknownhash

See LICENSE.txt for license information.
PS I:\src\vcpkg> .\vcpkg install  tensorflow[*]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    tensorflow[core]:x64-windows -> 2.3.1#1
  * tensorflow-common[core]:x64-windows -> 2.3.1#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\mmd\AppData\Local\vcpkg\archives\61\6116b2e1977f71d193a848d5d619519f571a928d.zip
Could not locate cached archive: C:\Users\mmd\AppData\Local\vcpkg\archives\a0\a097cb8518b6a580902ab39dd5f556338c5d670d.zip
Starting package 1/2: tensorflow-common:x64-windows
Building package tensorflow-common[core]:x64-windows...
-- Installing: I:/src/vcpkg/packages/tensorflow-common_x64-windows/share/tensorflow-common/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\mmd\AppData\Local\vcpkg\archives\61\6116b2e1977f71d193a848d5d619519f571a928d.zip
Building package tensorflow-common[core]:x64-windows... done
Installing package tensorflow-common[core]:x64-windows...
Installing package tensorflow-common[core]:x64-windows... done
Elapsed time for package tensorflow-common:x64-windows: 2.666 s
Starting package 2/2: tensorflow:x64-windows
Building package tensorflow[core]:x64-windows...
-- Using msys root at I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b
-- Using cached I:/src/vcpkg/downloads/tensorflow-tensorflow-v2.3.1.tar.gz
-- Applying patch I:/src/vcpkg/installed/x64-windows/share/tensorflow-common/fix-build-error.patch
-- Applying patch I:/src/vcpkg/installed/x64-windows/share/tensorflow-common/fix-dbg-build-errors.patch
-- Applying patch I:/src/vcpkg/installed/x64-windows/share/tensorflow-common/fix-more-build-errors.patch
-- Using source at I:/src/vcpkg/buildtrees/tensorflow/src/v2.3.1-3bb65f15d0.clean
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/usr/bin/bash.exe --noprofile --norc -c "'I:/src/vcpkg/downloads/tools/bazel/3.7.0-windows/bazel.exe' build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    See logs for more information:
      I:\src\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:219 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:136 (include)

Error: Building package tensorflow:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

$TEST_TMPDIR defined: output root default is 'i:\src\vcpkg\buildtrees\.bzl' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/lib/python3.8/site-packages --python_path=I:/src/vcpkg/downloads/tools/msys2/7030ad0251a2377b/mingw64/bin/python3.exe --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file i:\src\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define framework_shared_object=false
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
Analyzing: 2 targets (7 packages loaded, 11 targets configured)
Analyzing: 2 targets (81 packages loaded, 1659 targets configured)
Analyzing: 2 targets (98 packages loaded, 2377 targets configured)
Analyzing: 2 targets (122 packages loaded, 3416 targets configured)
Analyzing: 2 targets (140 packages loaded, 3958 targets configured)
Analyzing: 2 targets (159 packages loaded, 5647 targets configured)
Analyzing: 2 targets (162 packages loaded, 7179 targets configured)
WARNING: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/core/BUILD:1749:11: in linkstatic attribute of cc_library rule //tensorflow/core:lib_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
Analyzing: 2 targets (173 packages loaded, 10218 targets configured)
WARNING: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/core/BUILD:2161:16: in linkstatic attribute of cc_library rule //tensorflow/core:framework_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
Analyzing: 2 targets (174 packages loaded, 11226 targets configured)
INFO: Repository aws instantiated at:
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:19:16: in <toplevel>
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace.bzl:108:27: in tf_repositories
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace.bzl:49:8: in initialize_third_party
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/aws/workspace.bzl:9:29: in repo
Repository rule third_party_http_archive defined at:
  I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:219:43: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class java.io.IOException Tried to reconnect at offset 12,729,763 but server didn't support it
ERROR: An error occurred during the fetch of repository 'aws':
   Traceback (most recent call last):
	File "I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl", line 188, column 33, in _third_party_http_archive
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz, https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz] to I:/src/vcpkg/buildtrees/.bzl/_bazel_mmd/gedkvm5a/external/aws/temp1096286104503363444/1.7.336.tar.gz: Tried to reconnect at offset 12,729,763 but server didn't support it
ERROR: I:/src/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/core/platform/s3/BUILD:76:11: //tensorflow/core/platform/s3:s3_file_system depends on @aws//:aws in repository @aws which failed to fetch. no such package '@aws//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz, https://github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz] to I:/src/vcpkg/buildtrees/.bzl/_bazel_mmd/gedkvm5a/external/aws/temp1096286104503363444/1.7.336.tar.gz: Tried to reconnect at offset 12,729,763 but server didn't support it
ERROR: Analysis of target '//tensorflow:install_headers' failed; build aborted: Analysis failed
INFO: Elapsed time: 1100.858s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (174 packages loaded, 11226 targets configured)
FAILED: Build did NOT complete successfully (174 packages loaded, 11226 targets configured)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
the point is the folder (I:/src/vcpkg/buildtrees/.bzl/_bazel_mmd/gedkvm5a/external/aws/temp1096286104503363444) is randomly generated , i cant  copy 1.7.336.tar.gz to this folder.

**Comment by jgehw** [comment]
@kuelite Do you have a proxy configured on your machine? This unfortunately breaks things because there are several (build) systems nested in each other (Windows -> vcpkg -> MSYS2 -> Bazel -> Java) and not all correctly "forward" proxy configurations and CA root certificates to each other (CA root certificates might be needed if your antivirus solution does https scanning).

To fix this, I added support for several environment variables. If you have a proxy on IP 10.1.1.1 and port 8080, you need to set the following before calling `vcpgk.exe` (note that it's `http://` both times, not `https://` for the second variable):
```
set HTTP_PROXY=http://10.1.1.1:8080/
set HTTPS_PROXY=http://10.1.1.1:8080/
```
If your antivirus solution installed a CA root certificate on your machine to scan https traffic, you need to export it in PEM format (run `mmc`, add snap-in "certificates", find the certifcate in "trusted root CAs" folder and export it); find the `cacerts` file inside your Java installation (or the temporary Java installation inside the `buildtrees\.bzl` folder, or download Java and extract it), copy it somewhere, e.g. `C:\my_cacerts`, and add the exported certificate in the PEM file via the `keytool` utility that is part of Java, e.g.:
```
keytool -keystore C:/my_cacerts -import -alias MyAntivirusSolutionName -file exported_certificate.pem
```
The default password of cacerts seems to be "changeit" on most Java installations. When done, set the following variables to convince Bazel to tell Java to use your cacerts file, and convince vcpkg to pass the variables to Bazel. Please pay attention to use forward slashes (not backslashes) in the `BAZEL_CUSTOM_CACERTS` variable because backslashes would get messed up on their way through all the (build) systems:
```
set BAZEL_CUSTOM_CACERTS=C:/my_cacerts
set BAZEL_CUSTOM_CACERTS_PASSWORD=changeit
set VCPKG_KEEP_ENV_VARS=BAZEL_CUSTOM_CACERTS;BAZEL_CUSTOM_CACERTS_PASSWORD
```
When done, you might run into the next error (like me): the innermost build system eventually invokes `git` to download dependencies; it doesn't use its own git but your Windows git installation; unfortunately, not all git installations can deal with being called via Windows -> vcpkg -> MSYS2 -> Bazel -> Java -> git (I had git installed from https://git-scm.com, which didn't work. I switched to https://gitforwindows.org, which worked. Apparently they both have the same code base, but are obviously built/linked slightly differently...). Finally, when we're so fed up at some point that you just want to suppress the SSL verification, you might stumble upon other pitfall: When git is invoked via Windows -> vcpkg -> MSYS2 -> Bazel -> Java -> git, it "thinks" that your home is below the MSYS2 installation, so it doesn't use `C:\Users\yourusername\.gitconfig` but `C:\path\to\vcpkg\downloads\tools\msys2\some_hex_code\home\yourusername\.gitconfig`, which doesn't exist, so you need to copy it there.

**Comment by jgehw** [comment]
@NancyLi1013 maybe it's worth to copy my how-to in the previous comment to some documentation section as it might affect more users?

**Comment by PhoebeHui** [comment]
Thanks @jgehw for the details! 

@kuelite, does this solve your problem?

**Comment by kuelite** [comment]
thank you in advance, i will take a look later



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月25日(星期二) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vcpkg] [tensorflow[*]:x64-windows] build failure (#15542)





 
Thanks @jgehw for the details!
 
@kuelite, does this solve your problem?

**Comment by LilyWangLL** [comment]
Ping @kuelite for response, does this issue still exist?

**Comment by FrankXie05** [comment]
@kuelite Is still work for this issue? I will close this issue, please open it if there is any progress。
