### ISSUE TITLE
[boost] Failed when build external libtorrent that uses boost library.

### ISSUE THREAD

**Issue by hksdpc250** [microsoft/vcpkg#17312]
**Describe the bug**
```
D:\vcpkg\installed\arm64-windows-static\include\boost/multiprecision/cpp_int/intel_intrinsics.hpp(103,11): error C3861:
 '_addcarry_u32': identifier not found
```

**Environment**
- OS: windows x64 cross compile to arm64
- Compiler: visual studio 2019

**To Reproduce**
1. ./vcpkg install --triplet=arm64-windows boost openssl
2. build latest libtorrent manually

**Expected behavior**
build success

**Failure logs** 
```
D:\libtorrent-rasterbar-2.0.3\build>vcpkg --triplet=arm64-windows-static install boost openssl
...................................
D:\libtorrent-rasterbar-2.0.3\build>cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="D:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="arm64-windows-static" -DBUILD_SHARED_LIBS=OFF -Dstatic_runtime=ON ..
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/MicrosoftVisualStudio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/MicrosoftVisualStudio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Found OpenSSL: D:/vcpkg/installed/arm64-windows-static/lib/libcrypto.lib (found version "1.1.1j")
-- Found Boost: D:/vcpkg/installed/arm64-windows-static/include (found version "1.75.0")
-- The following features have been enabled:

 * static_runtime, build libtorrent with static runtime
 * dht, enable support for Mainline DHT
 * deprecated-functions, enable deprecated functions for backwards compatibility
 * encryption, Enables encryption in libtorrent
 * exceptions, build with exception support
 * extensions, Enables protocol extensions
 * i2p, build with I2P support
 * logging, build with logging
 * mutable-torrents, Enables mutable torrent support
 * streaming, Enables support for piece deadline

-- The following RECOMMENDED packages have been found:

 * OpenSSL, Full-strength general purpose cryptography library, <https://www.openssl.org/>
   Provides HTTPS support to libtorrent

-- The following REQUIRED packages have been found:

 * Threads
 * Boost

-- The following features have been disabled:

 * BUILD_SHARED_LIBS, build libtorrent as a shared library
 * build_tests, build tests
 * build_examples, build examples
 * build_tools, build tools
 * python-bindings, build python bindings
 * python-egg-info, generate python egg info
 * python-install-system-dir, Install python bindings to the system installation directory rather than the CMake installation prefix
 * gnutls, build using GnuTLS instead of OpenSSL

-- Configuring done
-- Generating done
-- Build files have been written to: D:/libtorrent-rasterbar-2.0.3/build

D:\libtorrent-rasterbar-2.0.3\build>cmake --build .
[45/164] Building CXX object CMakeFiles\torrent-rasterbar.dir\src\peer_connection.cpp.obj
FAILED: CMakeFiles/torrent-rasterbar.dir/src/peer_connection.cpp.obj
D:\MicrosoftVisualStudio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\Hostx64\arm64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_EXCEPTION_DISABLE -DOPENSSL_NO_SSL2 -DTORRENT_BUILDING_LIBRARY -DTORRENT_SSL_PEERS -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE -D_FILE_OFFSET_BITS=64 -D_SCL_SECURE_NO_DEPRECATE -D_WIN32_WINNT=0x0600 -I..\include -I..\deps\try_signal -ID:\vcpkg\installed\arm64-windows-static\include /DWIN32 /D_WINDOWS /GR /EHsc /O2 /Ob2 /DNDEBUG -MT /Zc:__cplusplus /W4 /wd4251 /wd4275 /wd4373 /wd4268 /wd4503 /Zc:wchar_t /Zc:forScope /MP /bigobj /EHsc /showIncludes /FoCMakeFiles\torrent-rasterbar.dir\src\peer_connection.cpp.obj /FdCMakeFiles\torrent-rasterbar.dir\torrent-rasterbar.pdb /FS -c ..\src\peer_connection.cpp
D:\vcpkg\installed\arm64-windows-static\include\boost/multiprecision/cpp_int/intel_intrinsics.hpp(103): error C3861: '_addcarry_u32': identifier not found
D:\vcpkg\installed\arm64-windows-static\include\boost/multiprecision/cpp_int/intel_intrinsics.hpp(108): error C3861: '_subborrow_u32': identifier not found
[52/164] Building CXX object CMakeFiles\torrent-rasterbar.dir\src\http_connection.cpp.obj
ninja: build stopped: subcommand failed.
```
**Additional context**

**Comment by PhoebeHui** [comment]
@hksdpc250, the libtorrent with arm-windows or arm64-windows triplet doesn't support in vcpkg.

Also '_addcarry_u32' is only available on x86 processor, see https://docs.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=msvc-160. so this error should be a Upstream issue, could you report an issue to boost-multiprecision instead?

**Comment by hksdpc250** [comment]
It seems like this problem is solved by upstream, but only in the master branch just now.

Can we just apply this patch for arm64 before it release the boost 1.77?

**Comment by NancyLi1013** [comment]
> It seems like this problem is solved by upstream just now, but only in the master branch.
> 
> Can we just apply this patch for arm64 before they release boost 1.77?

Thanks for your information. I think we can make a patch for this fix before the new version 1.77 releases.

**Comment by BaptRo** [comment]
This bug still exist: 
https://github.com/boostorg/multiprecision/pull/331 

When cross compiling for windows ARM64 with `vs-professional-2019-16.10.3-msvc-14.29.30036-winsdk-10.0.19041.0` I get the following error:
```...\boost_1_78_0\boost/multiprecision/cpp_int/intel_intrinsics.hpp(118): error C3861: '_addcarry_u32': identifier not found```

**Comment by PhoebeHui** [comment]
@BaptRo, thanks for the information, currently vcpkg applies patch https://github.com/microsoft/vcpkg/blob/master/ports/boost-multiprecision/0001-Fix-selection-logic-in-intel_intrinsics.hpp.patch to fix the problem. Could you get latest source and try again?

**Comment by BaptRo** [comment]
After some [discussion](https://github.com/boostorg/multiprecision/issues/410) , it appears that this issue is fix on `develop` and should be released with `1.79` in the coming months. 
Thank you for the patch link 👍
