### ISSUE TITLE
[zstd] Failing to build package in azure devops pipeline - corrupt patch

### ISSUE THREAD

**Issue by adwodon** [microsoft/vcpkg#18334]
**Host Environment**
- OS:Windows
- Compiler: MSBuild 1.187.0

**To Reproduce**
Running a pipeline on azure devops - visual studio solution with manifest.

**Failure logs** 
```
Starting package 1/38: zstd:x64-windows
  Building package zstd[core]:x64-windows...
  -- Installing port from location: C:\WINDOWS\ServiceProfiles\NetworkService\AppData\Local\vcpkg\registries\git-trees\3a0ffa2a8fe8246a3937d9f6a77d577e351dd445
  -- Using C:/vcpkg/downloads/facebook-zstd-v1.4.9.tar.gz
  -- Extracting source C:/vcpkg/downloads/facebook-zstd-v1.4.9.tar.gz
  -- Applying patch install_pkgpc.patch
  CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:61 (message):
##[error]Applying patch failed(0,0): Error : corrupt patch at line 8
Applying patch failed : error : corrupt patch at line 8 [C:\agent\_work\1\s\trz-common\trz-common.vcxproj]
  
  Call Stack (most recent call first):
    scripts/cmake/vcpkg_extract_source_archive_ex.cmake:144 (z_vcpkg_apply_patches)
    scripts/cmake/vcpkg_from_github.cmake:154 (vcpkg_extract_source_archive_ex)
    C:/Windows/ServiceProfiles/NetworkService/AppData/Local/vcpkg/registries/git-trees/3a0ffa2a8fe8246a3937d9f6a77d577e351dd445/portfile.cmake:1 (vcpkg_from_github)
    scripts/ports.cmake:139 (include)
  
  
##[error]EXEC(0,0): Error : Building package zstd:x64-windows failed with: BUILD_FAILED
EXEC : error : Building package zstd:x64-windows failed with: BUILD_FAILED [C:\agent\_work\1\s\trz-common\trz-common.vcxproj]
  Please ensure you're using the latest portfiles with `.\vcpkg update`, then
  submit an issue at https://github.com/Microsoft/vcpkg/issues including:
    Package: zstd:x64-windows
    Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
  
  Additionally, attach any relevant sections from the log files above.

```

**Additional context**
This is on our remote build machine, it seems to be an environmental issue as I can run either the msbuild command, or inner vcpkg command locally and it will succeed:

```
  "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\agent\_work\1\s\\" "--x-install-root=C:\agent\_work\1\s\vcpkg_installed\\" --feature-flags=registries
```

```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\msbuild.exe" "C:\agent\_work\1\s\MySolution.sln" /nologo /nr:false /dl:CentralLogger,"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.187.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=a8916215-20b3-4a73-9be5-27db9656d0c2|SolutionDir=C:\agent\_work\1\s"*ForwardingLogger,"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.187.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"  /p:platform="x64" /p:configuration="Debug" /p:VisualStudioVersion="16.0" /p:_MSDeployUserAgent="VSTS_b829fc00-0fa9-4e0d-974c-cc6ed349e840_build_24_0"
```

However when running through devops it will fail with the above error on zstd every time.  I have updated the agent, which clears out the directory fully, vcpkg version is new as of today, see version above.

It seems fine so I am really baffled as to whats going on.

I am running this to test out manifests and registries for our solution.

**Comment by JackBoosY** [comment]
This issue should be fixed, can you confirm your vcpkg is latest?

**Comment by PhoebeHui** [comment]
It looks same issue with https://github.com/microsoft/vcpkg/issues/16955

**Comment by adwodon** [comment]
@JackBoosY the logs show
` Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9`

I went onto the build machine, did a git pull & ran the boostrap to confirm, still the same vcpkg version when using the `vcpkg version` command and still the same issue.

Just to be clear, this only happens when this is run through an azure devops agent, running vcpkg from the command line works just fine, even launching msbuild from the command line succeeds, as does building the solution in Visual Studio directly.

Here are the full job logs:
[zstd_vcpkg_build_fail.txt](https://github.com/microsoft/vcpkg/files/6621858/zstd_vcpkg_build_fail.txt)

**Comment by JackBoosY** [comment]
@strega-nil-ms Seems our changes didn't fix this issue.

**Comment by trebconnell** [comment]
I'm seeing this vcpkg latest installing opencv4[core] in Windows on devops pipelines...  I'm investigating and will report back if I discover anything.

Reproduced with commit hash: 633f3e0c130a466beadb1f0cbd3ae3c55859565a

**Comment by Adela0814** [comment]
I'm not able to repro this issue with the latest `vcpkg `version, if it is still an issue, please reopen it.
