### ISSUE TITLE
[pangolin] Problems with installed library

### ISSUE THREAD

**Issue by bakelew** [Microsoft/vcpkg#1866]
Windows 10 x64, Visual Studio 14 Community Edition
Port: pangolin, 0.5-1
vcpkg: 0.0.89-2017-09-23-67e876c76555c466e4faf49d6cd80a88b835f972

After getting pangolin to install with [this issue](https://github.com/Microsoft/vcpkg/issues/1865), and running `vcpkg integrate install`, and creating a sample project such as [HelloPangolin](https://github.com/stevenlovegrove/Pangolin/blob/master/examples/HelloPangolin/main.cpp), the sample is unable to build with 403 errors inside Error List window, and one fatal error in build Output window:

> 1>c:\users\USER\myprograms\vcpkg\installed\x64-windows\include\pangolin\platform.h(52): fatal error C1083: Cannot open include file: 'pangolin/pangolin_export.h': No such file or directory

By manually copying the file pangolin_export.h from buildtrees\pangolin\x64-windows-rel\src\include\pangolin to installed\x64-windows\include\pangolin, the error changes from the above to:

> 1>c:\users\USER\myprograms\vcpkg\installed\x64-windows\include\pangolin\gl\glplatform.h(56): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory

Very lost, and personally giving up for now. Perhaps it should be investigated if we can just use vcpkg ports of the pangolin dependencies.

**Comment by paul-michalik** [comment]
Definitely! We have a port of pangolin integration in my vcpkg fork which does that with absolutely zero problems.

**Comment by alexkaratarakis** [comment]
Please try with the updated port that picks dependencies from vcpkg.

**Comment by bakelew4953** [comment]
Thank you very much, I am trying the new version now:
`vcpkg install pangolin:x64-windows` with latest vcpkg version 0.0.90-2017-09-25-fe92af4ddd6ab409e013208ce131a40e333c0ba8.

I create new blank VS 2014 project, and copy-paste the HelloPangolin code. From here, it will only build if I specify "OpenGl32.lib" in Linker -> Input.

Once this is done, Release mode executes as expected, however Debug mode is missing glew32.dll in the executable directory, and does not start execution.

Looks very close, thank you for your work :)

**Comment by alexkaratarakis** [comment]
There is an `opengl` port that should take care of that for you. Try:
`vcpkg install opengl:x64-windows`

**Comment by bakelew4953** [comment]
Thank you, I did this, now I no longer need to specify "OpenGl32.lib" in Linker -> Input. 

However, debug mode still does not find glew32.dll. Perhaps it should be searching for glew32d.dll? Since vcpkg builds debug glew version with the *d.dll suffix.

I tried adding:
> string(REPLACE "lib/glew32.lib" "debug/lib/glew32d.lib" PANGOLIN_TARGETS "${PANGOLIN_TARGETS}")

Below line 37 in portfile.cmake, then re-install pangolin, but this did not seem to make any difference (probably because I have no idea what I am doing). 

I have also tried manually copying glew32d.dll and renaming to glew32.dll. When I do this, HelloPangolin executes in debug mode, but crashes when I click the window with error message "Run-Time Check Failure #2 - Stack around the variable 'T_wc' was corrupted."

Wish I could be of more help 🤒

**Comment by alexkaratarakis** [comment]
@bakelew4953 
133099fa2c46152474cfab052d0d1bcbc83749f2 should fix this issue.
It was indeed pulling in the wrong flavor of `glew`.

**Comment by bakelew4953** [comment]
@alexkaratarakis 
Thank you! 

This fixes the missing glew32d.dll issue, but I still get the error when running x64 Debug configuration that says "Run-Time Check Failure #2 - Stack around the variable 'T_wc' was corrupted". This error does not occur in Release mode. 

Could this be an issue in the library source?

**Comment by JackBoosY** [comment]
Hi @bakelew @paul-michalik  @alexkaratarakis , thanks for reporting this issue!
I have fixed this issue in #5647. Please update and rebuild it.
Thx.
