### ISSUE TITLE
Custom standard intermediate and output directories fail bootstrap.ps1

### ISSUE THREAD

**Issue by BeErikk** [microsoft/vcpkg#1919]
In case you have custom standard intermediate and output directories, `bootstrap.ps1` fails.

For example like I have in my `Microsoft.Cpp.x64.user.props`
`   <IgnoreWarnIntDirInTempDetected>true</IgnoreWarnIntDirInTempDetected> 
    <OutDir>$(SolutionDir)bin\$(PlatformName)_$(Configuration)\</OutDir>
    <IntDir>$(TEMP)\$(SolutionName)\$(ProjectName)\$(PlatformName)_$(Configuration)\</IntDir>`

Here is a working patch
[bootstrap.ps1.diff.txt](https://github.com/Microsoft/vcpkg/files/1354622/bootstrap.ps1.diff.txt)

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

This _may_ cause issues when building packages as well. We'll investigate further.

**Comment by BeErikk** [comment]
I did a pull and noticed that` bootstrap.ps1` have been updated, but my patch didn't make it. So I thought I'd supply an updated patch and hope it will succeed. Thanks for your remark. I really hope having a _custom intermediate directory_ in Visual Studio doesn't break `vcpkg` when building packages.

[bootstrap.ps1.patch.txt](https://github.com/Microsoft/vcpkg/files/1443311/bootstrap.ps1.patch.txt)

**Comment by NancyLi1013** [comment]
@BeErikk 

This issue should be fixed. Please update vcpkg and try it again. I cannot reproduce this on my local now.

**Comment by BeErikk** [comment]
No, it's not fixed. The issue is a hardcoded output path in the script which rely on Visual Studio having unspecified standard output and intermediate paths. It is not uncommon to have intermediate files redirected to some temporary directories and custom standard template as the output path. The solution, in this case, is simply to specify the output directory in the linker options.

**Comment by NancyLi1013** [comment]
Sorry, I might not understand this issue correctly. So I just add `"/p:OutDir=$vcpkgReleaseDir\"` to test. If this issue still needs to be fixed, please feel free to reopen this.

**Comment by BeErikk** [comment]
Thanks for looking into this, but well, the `user.props` files (and the earlier `.vsprops` files) have been deprecated in VS 2019 and its use made somewhat impossible in favour for other behaviours, so I guess the issue is no longer.
