### ISSUE TITLE
 Package: boost-regex:x86-windows-static : build failure

### ISSUE THREAD

**Issue by apdams** [microsoft/vcpkg#20769]
**Host Environment**
- OS: Windows 10
- Compiler: VS2019

**To Reproduce**
Steps to reproduce the behavior: Run the following command:

`./vcpkg install boost:x86-windows-static `

This is with a recently pulled version from github and I have run .\vcpkg update

**Failure logs** This is the output from the command prompt:

-- Extracting source C:/_gitdev/Cognite POC/vcpkg/downloads/boostorg-regex-boost-1.77.0.tar.gz
-- Using source at C:/_gitdev/Cognite POC/vcpkg/buildtrees/boost-regex/src/ost-1.77.0-3dc3b8cc79.clean
-- Including C:/_gitdev/Cognite POC/vcpkg/ports/boost-regex/b2-options.cmake
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:157 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-regex/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:141 (include)

Error: Building package boost-regex:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows-static
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by y43d** [comment]
> Yes, since it use the build tools from x64-windows, since the boost has been upgrade to 1.77, so the build tool should be updated, how about execute './vcpkg remove boost-build:x64-windows" and ./vcpkg install boost-regex:x86-windows-static?

I tried this, still received the same error.

> could you install it with '--debug' option and provide us the output?

@PhoebeHui 
I will do this now, here is my output:

(it's too long to post here, I made a paste)
[https://pastebin.com/B5Aeegu7](https://pastebin.com/B5Aeegu7)

**Comment by dg0yt** [comment]
@apdams I think you simply missed the latest commit which added the vcpkg-cmake dependency to boost-regex.

**Comment by PhoebeHui** [comment]
@y43d, could you please execute './vcpkg remove boost-modular-build-helper:x64-windows --recurse', and get latest source via 'git pull' and try again, it should solve the problems.

**Comment by y43d** [comment]
@PhoebeHui I did that... looks like i'm still getting the error.
Here are debug logs again (you can see me run git pull in there also.)

https://pastebin.com/a2CVFwbh

**Comment by y43d** [comment]
Weird, but yes, it's there.
![image](https://user-images.githubusercontent.com/76844813/138042149-4eeaf3cb-b41a-4127-8b5d-541d393b5f92.png)

**Comment by PhoebeHui** [comment]
Could you try to execute './vcpkg remove vcpkg-cmake:x64-windows --recurse' and try again?

**Comment by yurybura** [comment]
@y43d Please upload console output too to check installation plan? Like this:
```
D:\libs\vcpkg>vcpkg install boost:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
    boost[core]:x86-windows-static -> 1.77.0#2
  * boost-accumulators[core]:x86-windows-static -> 1.77.0
  * boost-algorithm[core]:x86-windows-static -> 1.77.0
  * boost-align[core]:x86-windows-static -> 1.77.0
  * boost-any[core]:x86-windows-static -> 1.77.0
  * boost-asio[core]:x86-windows-static -> 1.77.0
  * boost-assign[core]:x86-windows-static -> 1.77.0
  * boost-atomic[core]:x86-windows-static -> 1.77.0
  * boost-beast[core]:x86-windows-static -> 1.77.0
  * boost-bimap[core]:x86-windows-static -> 1.77.0
  * boost-callable-traits[core]:x86-windows-static -> 1.77.0
  * boost-chrono[core]:x86-windows-static -> 1.77.0
  * boost-compatibility[core]:x86-windows-static -> 1.77.0
  * boost-compute[core]:x86-windows-static -> 1.77.0
  * boost-container[core]:x86-windows-static -> 1.77.0
  * boost-context[core]:x86-windows-static -> 1.77.0
  * boost-contract[core]:x86-windows-static -> 1.77.0
  * boost-convert[core]:x86-windows-static -> 1.77.0
  * boost-coroutine[core]:x86-windows-static -> 1.77.0
  * boost-coroutine2[core]:x86-windows-static -> 1.77.0
  * boost-crc[core]:x86-windows-static -> 1.77.0
  * boost-date-time[core]:x86-windows-static -> 1.77.0
  * boost-describe[core]:x86-windows-static -> 1.77.0
  * boost-dll[core]:x86-windows-static -> 1.77.0
  * boost-dynamic-bitset[core]:x86-windows-static -> 1.77.0
  * boost-endian[core]:x86-windows-static -> 1.77.0
  * boost-exception[core]:x86-windows-static -> 1.77.0
  * boost-fiber[core]:x86-windows-static -> 1.77.0
  * boost-filesystem[core]:x86-windows-static -> 1.77.0
  * boost-flyweight[core]:x86-windows-static -> 1.77.0
  * boost-foreach[core]:x86-windows-static -> 1.77.0
  * boost-format[core]:x86-windows-static -> 1.77.0
  * boost-functional[core]:x86-windows-static -> 1.77.0
  * boost-geometry[core]:x86-windows-static -> 1.77.0
  * boost-gil[core]:x86-windows-static -> 1.77.0#1
  * boost-graph[core]:x86-windows-static -> 1.77.0
  * boost-hana[core]:x86-windows-static -> 1.77.0
  * boost-heap[core]:x86-windows-static -> 1.77.0
  * boost-histogram[core]:x86-windows-static -> 1.77.0
  * boost-hof[core]:x86-windows-static -> 1.77.0
  * boost-icl[core]:x86-windows-static -> 1.77.0
  * boost-interprocess[core]:x86-windows-static -> 1.77.0
  * boost-interval[core]:x86-windows-static -> 1.77.0
  * boost-intrusive[core]:x86-windows-static -> 1.77.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x86-windows-static -> 1.77.0#1
  * boost-json[core]:x86-windows-static -> 1.77.0
  * boost-lambda[core]:x86-windows-static -> 1.77.0
  * boost-lambda2[core]:x86-windows-static -> 1.77.0
  * boost-leaf[core]:x86-windows-static -> 1.77.0
  * boost-lexical-cast[core]:x86-windows-static -> 1.77.0
  * boost-local-function[core]:x86-windows-static -> 1.77.0
  * boost-locale[core]:x86-windows-static -> 1.77.0
  * boost-lockfree[core]:x86-windows-static -> 1.77.0
  * boost-log[core]:x86-windows-static -> 1.77.0
  * boost-logic[core]:x86-windows-static -> 1.77.0
  * boost-math[core]:x86-windows-static -> 1.77.0
  * boost-metaparse[core]:x86-windows-static -> 1.77.0
  * boost-msm[core]:x86-windows-static -> 1.77.0
  * boost-multi-array[core]:x86-windows-static -> 1.77.0
  * boost-multi-index[core]:x86-windows-static -> 1.77.0
  * boost-multiprecision[core]:x86-windows-static -> 1.77.0
  * boost-nowide[core]:x86-windows-static -> 1.77.0
  * boost-odeint[core]:x86-windows-static -> 1.77.0#1
  * boost-outcome[core]:x86-windows-static -> 1.77.0
  * boost-parameter-python[core]:x86-windows-static -> 1.77.0
  * boost-pfr[core]:x86-windows-static -> 1.77.0
  * boost-phoenix[core]:x86-windows-static -> 1.77.0
  * boost-poly-collection[core]:x86-windows-static -> 1.77.0
  * boost-polygon[core]:x86-windows-static -> 1.77.0
  * boost-pool[core]:x86-windows-static -> 1.77.0
  * boost-process[core]:x86-windows-static -> 1.77.0#2
  * boost-program-options[core]:x86-windows-static -> 1.77.0
  * boost-property-map[core]:x86-windows-static -> 1.77.0
  * boost-property-tree[core]:x86-windows-static -> 1.77.0
  * boost-proto[core]:x86-windows-static -> 1.77.0
  * boost-ptr-container[core]:x86-windows-static -> 1.77.0
  * boost-python[core,python3]:x86-windows-static -> 1.77.0#1
  * boost-qvm[core]:x86-windows-static -> 1.77.0
  * boost-random[core]:x86-windows-static -> 1.77.0
  * boost-range[core]:x86-windows-static -> 1.77.0
  * boost-ratio[core]:x86-windows-static -> 1.77.0
  * boost-rational[core]:x86-windows-static -> 1.77.0
  * boost-safe-numerics[core]:x86-windows-static -> 1.77.0
  * boost-scope-exit[core]:x86-windows-static -> 1.77.0
  * boost-serialization[core]:x86-windows-static -> 1.77.0
  * boost-signals2[core]:x86-windows-static -> 1.77.0
  * boost-sort[core]:x86-windows-static -> 1.77.0
  * boost-spirit[core]:x86-windows-static -> 1.77.0
  * boost-stacktrace[core]:x86-windows-static -> 1.77.0
  * boost-statechart[core]:x86-windows-static -> 1.77.0
  * boost-static-string[core]:x86-windows-static -> 1.77.0
  * boost-stl-interfaces[core]:x86-windows-static -> 1.77.0
  * boost-system[core]:x86-windows-static -> 1.77.0
  * boost-test[core]:x86-windows-static -> 1.77.0
  * boost-thread[core]:x86-windows-static -> 1.77.0
  * boost-timer[core]:x86-windows-static -> 1.77.0
  * boost-tokenizer[core]:x86-windows-static -> 1.77.0
  * boost-tti[core]:x86-windows-static -> 1.77.0
  * boost-type-erasure[core]:x86-windows-static -> 1.77.0
  * boost-ublas[core]:x86-windows-static -> 1.77.0
  * boost-units[core]:x86-windows-static -> 1.77.0
  * boost-unordered[core]:x86-windows-static -> 1.77.0
  * boost-uuid[core]:x86-windows-static -> 1.77.0
  * boost-variant[core]:x86-windows-static -> 1.77.0
  * boost-variant2[core]:x86-windows-static -> 1.77.0
  * boost-vmd[core]:x86-windows-static -> 1.77.0
  * boost-wave[core]:x86-windows-static -> 1.77.0
  * boost-xpressive[core]:x86-windows-static -> 1.77.0
  * boost-yap[core]:x86-windows-static -> 1.77.0
  * bzip2[core]:x86-windows-static -> 1.0.8#2
  * expat[core]:x86-windows-static -> 2.4.1
  * liblzma[core]:x86-windows-static -> 5.2.5#3
  * openssl[core]:x86-windows-static -> 1.1.1l#2
  * python3[core]:x86-windows-static -> 3.10.0
  * vcpkg-cmake-config[core]:x64-windows -> 2021-09-27
  * zlib[core]:x86-windows-static -> 1.2.11#13
  * zstd[core]:x86-windows-static -> 1.5.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static...
```

**Comment by PhoebeHui** [comment]
Restored 39 packages from C:\Users\phila\AppData\Local\vcpkg\archives in 3.132 s. Use --debug to see more details.

It looks restore the packages from binary cache, so even these ports has been uninstalled. It's still use cache file. Could you clone a clean source and see if the issue repro?

1. git clone https://github.com/microsoft/vcpkg
2. cd vcpkg
3. ./bootstrap-vcpkg.bat
4. ./vcpkg install boost-regex:x86-windows-static

If you don't want to clean a new source, you can try below steps:
1. Git pull
2.  Delete  C:\Users\phila\AppData\Local\vcpkg\archives
2. ./vcpkg remove boost-uninstall:x64-windows --recurse
3. ./vcpkg remove boost-uninstall:x86-windows-static --recurse
4. ./vcpkg install boost-regex:x86-windows-static

**Comment by PhoebeHui** [comment]
@y43d, could you provide us the following build logs?
vcpkg\buildtrees\boost-regex\install-x86-windows-static-rel-out.log
vcpkg\buildtrees\boost-regex\x86-windows-static-rel\CMakeFiles\CMakeOutput.log
\vcpkg\buildtrees\boost-regex\x86-windows-static-rel\boost\config.log
