### ISSUE TITLE
[Armadillo] build failure

### ISSUE THREAD

**Issue by genisispig** [microsoft/vcpkg#20773]
**Host Environment**
- OS: Windows 10
- Compiler: MVSC v142

**To Reproduce**
`./vcpkg install armadillo:x64-windows`
Within CMakeLists.txt:
`find_package(Armadillo CONFIG REQUIRED)`
`target_link_libraries(main PRIVATE ${ARMADILLO_LIBRARIES})`

**Failure logs** 

```CMake Error at C:/dev/vcpkg/vcpkg/installed/x64-windows/share/Armadillo/ArmadilloConfig.cmake:12 (include):
  include could not find requested file:

    /share/Armadillo/ArmadilloLibraryDepends.cmake		
C:/dev/vcpkg/vcpkg/installed/x64-windows/share/Armadillo/ArmadilloConfig.cmake	12	
````

Upon looking at the above folder, the file that it is unable to find is in fact there.

**Additional context**

This is the same error as https://github.com/microsoft/vcpkg/issues/8480#issue-503571107

Listed armadillo version on sourceforge is ahead of the vcpkg version: 
http://arma.sourceforge.net/download.html
https://vcpkg.info/port/armadillo

**Comment by JonLiu1993** [comment]
Confirmed

**Comment by PhoebeHui** [comment]
It look this issue has been solved. @genisispig, does this still be a problem for you?

**Comment by genisispig** [comment]
@PhoebeHui I'm still experiencing the issue with the ArmadilloLibraryDepends file mentioned above. Do you have a reference for which PR would have fixed the issue? I thought I was waiting on #20439 for this to be fixed.

**Comment by PhoebeHui** [comment]
Yeah, I have updated that PR, it should be merged soon once the CI testing passed.

**Comment by genisispig** [comment]
Sounds good!

**Comment by JackBoosY** [comment]
Close this issue via #20439 merged.
