### ISSUE TITLE
Failed to build double-conversion:x64-windows

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/vcpkg#2103]
I encountered the following issue when build folly by vcpkg latest revision 'fae64c5'.

See the failures:

D:\VCPKG\src>vcpkg install double-conversion:x64-windows
The following packages will be built and installed:
    double-conversion:x64-windows
Starting package 1/1: double-conversion:x64-windows
Building package double-conversion:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/VCPKG/src/installed/x64-windows
-- DOWNLOADS=D:/VCPKG/src/downloads
-- CURRENT_PACKAGES_DIR=D:/VCPKG/src/packages/double-conversion_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/VCPKG/src/buildtrees/double-conversion
-- CURRENT_PORT_DIR=D:/VCPKG/src/ports/double-conversion/.
-- Using cached D:/VCPKG/src/downloads/google-double-conversion-v3.0.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/VCPKG/src/ports/double-conversion/001-fix-arm.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/VCPKG/src/ports/double-conversion/001-fix-arm.patch done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Performing post-build validation
/debug/share should not exist. Please reorganize any important files, then use
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
Found 1 error(s). Please correct the portfile:
    D:\VCPKG\src\ports\double-conversion\portfile.cmake
-- Performing post-build validation done
Error: Building package double-conversion:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: double-conversion:x64-windows
  Vcpkg version: 0.0.95

Additionally, attach any relevant sections from the log files above.

**Comment by darke1891** [comment]
Hi, I got the same error.
Then I try `vcpkg install double-conversion:x64-windows --head`, and `vcpkg` install `double-conversion` successfully.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue! I've pushed a fix to master as `double-conversion` `3.0.0-2`.

**Comment by xiasun** [comment]
Hi, @ras0219-msft , this issue still appears with me. I am using VS 2015 update 3 and vcpkg 0.0.110. 
Thank you.

Error: Building package double-conversion:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: double-conversion:x64-windows
  Vcpkg version: 0.0.110-2018-04-28-a9d989ec056246ea320a56ca7d02b161a6fee387

Additionally, attach any relevant sections from the log files above.

**Comment by xiasun** [comment]
Sorry this is due to the proxy problem. Installed successfully after setting proxy. Thank you.
