### ISSUE TITLE
[aws-sdk-cpp] build failure on macOS when targeting macOS 10.9

### ISSUE THREAD

**Issue by Mike4Online** [microsoft/vcpkg#21445]
**Host Environment**
- OS: macOS 10.14 Mojave
- Compiler: AppleClang 11.0.0.11000033

**To Reproduce**

1) Add the following to `~/.bash_profile`:
`export MACOSX_DEPLOYMENT_TARGET=10.9`
`export VCPKG_KEEP_ENV_VARS=MACOSX_DEPLOYMENT_TARGET`

2) Then re-load `.bash_profile` with
`cd ~`
`source .bash_profile`

Then build the AWS SDK for S3 with:
`./vcpkg install openssl[core]:x64-osx --no-binary-caching`
`./vcpkg install aws-sdk-cpp[s3]:x64-osx --no-binary-caching`

The above environment variable should force the build to target macOS 10.9 or newer.  The build logs will show that `-mmacosx-version-min` is being set to `10.9`, as expected; however, the build will fail with compiler errors when building `aws-s3-sdk`, specifically when building `/aws-cpp-sdk-core/source/aws/core/utils/crypto/commoncrypto/CryptoImpl.cpp`.  This file compiles different CommonCrypto classes depending on the macOS version.  But on macOS 10.14 Mojave with `MACOSX_DEPLOYMENT_TARGET=10.9`, it will try to build classes that 10.9 does not support.

**Additional context**
A work-around that succeeded for me was to create a custom port that modifies the header file `/aws-cpp-sdk-core/include/aws/core/utils/crypto/commoncrypto/CryptoImpl.h` so that the `#if` block starting at Line 13 and ending at Line 19 is completely commented out.  This ensures `CryptoImpl.cpp` will build classes supported on older macOS versions, including 10.9.

A far preferable way to do this would be to enhance `vcpkg` so you could optionally  specify one or more preprocessor definitions on the `vcpkg` command line, as is supported by CMake, Make and many other command line build tools.  In this case, you could set `-D__MAC_OS_X_VERSION_MAX_ALLOWED=1090` on the `vcpkg` command line.  Defining this preprocessor macro on the command line is suggested by Apple; the following is an excerpt of comments in macOS SDK header [Availability.h](https://opensource.apple.com/source/xnu/xnu-2050.18.24/EXTERNAL_HEADERS/Availability.h.auto.html):

> The upper bound for the OS version is rarely needed, but it can be set on the command line via: `-D__MAC_OS_X_VERSION_MAX_ALLOWED=10xx` for Mac OS X...

**Comment by JackBoosY** [comment]
Also, I can't repro this issue, can you please provide the failure logs?

Thanks.

**Comment by Mike4Online** [comment]
I'll upload failure logs tomorrow.

**Comment by Mike4Online** [comment]
Here is a build log showing the compiler errors encountered when building `aws-sdk-cpp` while `MACOSX_DEPLOYMENT_TARGET` is set to `10.9`.

[vcpkg-build-of-aws-s3-sdk-error-targeting-macos-10-9.log](https://github.com/microsoft/vcpkg/files/7549603/vcpkg-build-of-aws-s3-sdk-error-targeting-macos-10-9.log)

**Comment by Mike4Online** [comment]
And here's the console output, as well as a full set of log files (zipped).

[aws-sdk-cpp_console_output_compiler_error.txt](https://github.com/microsoft/vcpkg/files/7549732/aws-sdk-cpp_console_output_compiler_error.txt)

[aws-sdk-cpp-logs.zip](https://github.com/microsoft/vcpkg/files/7549741/aws-sdk-cpp-logs.zip)

**Comment by Mike4Online** [comment]
Here's the custom port I wrote which allows aws-sdk-cpp to build successfully while `MACOSX_DEPLOYMENT_TARGET` is set to `10.9`.

[aws-sdk-cpp-logs.zip](https://github.com/microsoft/vcpkg/files/7549760/aws-sdk-cpp-logs.zip)

**Comment by JackBoosY** [comment]
See [my comment](https://github.com/microsoft/vcpkg/issues/21443#issuecomment-971115832).

**Comment by Mike4Online** [comment]
I saw your comment in #21443; however, even when I am able to get past the issue:

[[s2n] build failure on macOS #21443](https://github.com/microsoft/vcpkg/issues/21443)

by building the port `openssl[core]:x64-osx` prior to building the port `aws-sdk-cpp[s3]:x64-osx`

this issue, #21445 still occurs.  I.E. the compiler errors still occur when targeting macOS 10.9 - unless the custom port I attached in an earlier comment is employed.

**Comment by Mike4Online** [comment]
I updated Step 1 in my first comment.  I.E. to replicate this issue, you need to set **two** environment variables in `~/.bash_profile`:

`export MACOSX_DEPLOYMENT_TARGET=10.9`
`export VCPKG_KEEP_ENV_VARS=MACOSX_DEPLOYMENT_TARGET`

then `source .bash_profile` before building the port `aws-sdk-cpp[s3]:x64-osx`

**Comment by dg0yt** [comment]
In any case, port aws-sdk-cpp in vcpkg needs an update. Some of the issue with using it are already solved upstream. (Learned a few days ago from the attempt to use it in port netcdf-c.)

**Comment by Mike4Online** [comment]
I am looking forward to building with the updated port of `aws-cpp-sdk`.  Hopefully the new port will resolve this issue, too.

This issue is still flagged as **requires:more-information** and **requires:repro**.   If you need any more information from me, please let me know what you need.  

The inability to reproduce this issue was possibly due to me forgetting one of the two environment variables in my first post (now corrected, above).  Also, `.bash_profile` may not exist on some newer versions of macOS.  I am not sure the equivalent on newer macOS versions which use the Z shell rather than the bash shell.

**Comment by dg0yt** [comment]
Even if you could *build* port aws-sdk-cpp, it wouldn't mean you could really *use* it. For example, it is doing `include(FindOpenSSL)` instead of `find_package(OpenSSL)`, bypassing vcpkg's openssl wrapper...
But your instructions are useful to verify an updated version, if someone starts working on that.

**Comment by Mike4Online** [comment]
> Even if you could build port aws-sdk-cpp, it wouldn't mean you could really use it. For example, it is doing include(FindOpenSSL) instead of find_package(OpenSSL), bypassing vcpkg's openssl wrapper...

For what its worth, once I have built a set of static libraries with vcpkg, I copy the .a files to another folder and then link to these files directly, rather than relying on CMake files containing `find_package` or `find_library` to find the newly-built libraries.  So I am able to link my executables with the static libraries for OpenSSL, AWS SDK and other vcpkg-built libraries.

**Comment by JackBoosY** [comment]
aws-sdk-cpp was updated to 1.9.160 in vcpkg, is this issue resolved?

**Comment by Mike4Online** [comment]
Yes, this issue is resolved, thanks to a correction made to the s2n package; see https://github.com/microsoft/vcpkg/issues/21443
