### ISSUE TITLE
[pcl] build failure

### ISSUE THREAD

**Issue by chanduv1** [microsoft/vcpkg#21566]
```
D:\Project\Github\vcpkg>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
    pcl[core]:x86-windows -> 1.12.0
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\Chandu\AppData\Local\vcpkg\archives in 130.9 us. Use --debug to see more details.
Starting package 1/1: pcl:x86-windows
Building package pcl[core]:x86-windows...
-- Using cached PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz.
-- Cleaning sources at D:/Project/Github/vcpkg/buildtrees/pcl/src/89d532cf08-fd49a85837.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Project/Github/vcpkg/downloads/PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-find-qhull.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch pcl_config.patch
-- Applying patch pcl_utils.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-cmake_find_library_suffixes.patch
-- Using source at D:/Project/Github/vcpkg/buildtrees/pcl/src/89d532cf08-fd49a85837.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:485 (message):
  The following variables are not used in CMakeLists.txt:

      PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/pcl/portfile.cmake:42 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)


-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/Project/Github/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: D:/Project/Github/vcpkg/buildtrees/pcl/x86-windows-rel
    See logs for more information:
      D:\Project\Github\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core]:x86-windows -> 1.12.0
  vcpkg version: 709e9ec32 2021-11-19 (25 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.
```
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by chanduv1** [comment]
Config log file attached

 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7576165/config-x64-windows-out.log)

**Comment by autoantwort** [comment]
> See logs for more information:
D:\Project\Github\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

Please provide this file

**Comment by JackBoosY** [comment]
This should be fixed by my PR https://github.com/microsoft/vcpkg/pull/21276, can you please confirm that by git pull vcpkg and rebuild pcl?

Thanks.

**Comment by chanduv1** [comment]
> This should be fixed by my PR #21276, can you please confirm that by git pull vcpkg and rebuild pcl?
> 
> Thanks.

Hi,
Thanks for looking into the build error.

Tried reinstall and rebuild  ... Same issue persists. Uploading relevant logs for Reference.

Thanks,

D:\Project\Github\vcpkg>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
    pcl[core]:x86-windows -> 1.12.0#1
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.2.0). Downloading portable powershell-core v7.2.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/PowerShell-7.2.0-win-x86.zip -> D:\Project\Github\vcpkg\downloads\PowerShell-7.2.0-win-x86.zip
Extracting powershell-core...
Restored 0 packages from C:\Users\Chandu\AppData\Local\vcpkg\archives in 985 us. Use --debug to see more details.
Starting package 1/1: pcl:x86-windows
Building package pcl[core]:x86-windows...
-- Using cached PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz.
-- Extracting source D:/Project/Github/vcpkg/downloads/PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-find-qhull.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch pcl_config.patch
-- Applying patch pcl_utils.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-cmake_find_library_suffixes.patch
-- Applying patch fix-pkgconfig.patch
-- Applying patch fix-find-libusb.patch
-- Using source at D:/Project/Github/vcpkg/buildtrees/pcl/src/89d532cf08-7f45db68c8.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/Project/Github/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: D:/Project/Github/vcpkg/buildtrees/pcl/x86-windows-rel
    See logs for more information:
      D:\Project\Github\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:73 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core]:x86-windows -> 1.12.0#1
  vcpkg version: 30465138e 2021-11-22 (12 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7589748/install-x86-windows-rel-out.log)
.
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/7589751/stdout-x86-windows.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7589752/install-x86-windows-dbg-out.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7589757/config-x86-windows-out.log)

**Comment by JackBoosY** [comment]
```
D:\Project\Github\vcpkg\buildtrees\pcl\src\89d532cf08-7f45db68c8.clean\surface\src\3rdparty\opennurbs\opennurbs_lookup.cpp(670) : fatal error C1001: Internal compiler error.
(compiler file 'd:\a01\_work\20\s\src\vctools\Compiler\Utc\src\p2\main.c', line 217)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x69
  cl!RaiseException()+0x69
  cl!CloseTypeServerPDB()+0x7392b
  cl!CloseTypeServerPDB()+0x118591
```
It seems like a Visual Studio bug more than a port bug.

**Comment by JonLiu1993** [comment]
@chanduv1 ,Could you please provide your Visual Studio version?

**Comment by xbeheydt** [comment]
Hello, I have exacly same problem. Problem when install `release`.
Versions :
- Windows 11 ver. 21H2 build 22000.348
-  vcpkg version 2021.12.01
-  VisualStudio ver. 17.0.2

**Comment by JonLiu1993** [comment]
@chanduv1 ,@xbeheydt ,Confirmed this is a compiler bug. We have filed a bug to track this issue,
````
 fatal error C1001: Internal compiler error.
````
This error is same as https://github.com/microsoft/vcpkg/issues/19561#issuecomment-898879852, so I close this issue and we will track it in issue #19561
