### ISSUE TITLE
There is something wrong in my program while using vlfeat 

### ISSUE THREAD

**Issue by lunkyguy** [microsoft/vcpkg#22625]
the error is locate in generic.c:1312
void *
vl_malloc (size_t n)
{
  return (vl_get_state()->malloc_func)(n) ;
  //return (memalign)(32,n) ;
}
interrupted by signal 11: SIGSEGV
it runs well in win10,however occur in ubuntu20.04lts

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide a sample repro project?

**Comment by lunkyguy** [comment]
should I send my project via this email or post it on github?



At 2022-01-19 15:27:08, "LilyWangLL" ***@***.***> wrote:

Thanks for posting this issue. Could you please provide a sample repro project?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lunkyguy** [comment]
I put my code on this
[git@github.com:lunkyguy/vlfeat.git](url)

**Comment by LilyWangLL** [comment]
> I put my sample code on this [https://github.com/lunkyguy/vlfeat](url)

This link should be private, I can't access. If you can't provide repro codes, could you please provide the detail repro steps?

**Comment by lunkyguy** [comment]
This is my cmake project

从 Windows 版邮件发送

发件人: LilyWangLL
发送时间: 2022年1月20日 11:11
收件人: microsoft/vcpkg
抄送: zhouzl; Author
主题: Re: [microsoft/vcpkg] There is something wrong in my program whileusing vlfeat (Issue #22625)

I put my sample code on this https://github.com/lunkyguy/vlfeat
This link should be private, I can't access. If you can't provide repro codes, could you please provide the detail repro steps?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LilyWangLL** [comment]
> This is my cmake project,the input is jpg image [vlfeat_test.zip](https://github.com/microsoft/vcpkg/files/7902221/vlfeat_test.zip)

I will reproduce and confirm this issue soon.

**Comment by lunkyguy** [comment]
> > This is my cmake project,the input is jpg image [vlfeat_test.zip](https://github.com/microsoft/vcpkg/files/7902221/vlfeat_test.zip)
> 
> I will reproduce and confirm this issue soon.

thank you very much!

**Comment by lunkyguy** [comment]
I rebuild vlfeat using offical version vlfeat-0.9.21 and it works well,and the code in  error location is same,there maybe something wrong in buiding environment!

**Comment by LilyWangLL** [comment]
This issue has been solved, I am closing it for now.

**Comment by lunkyguy** [comment]
Sorry,the issue still exist,I build the libvl.so from officail version and it works well;
The problem still occurred in vcpkg vlfeat😂

从 Windows 版邮件发送

发件人: LilyWangLL
发送时间: 2022年3月4日 15:19
收件人: microsoft/vcpkg
抄送: zhouzl; Author
主题: Re: [microsoft/vcpkg] There is something wrong in my program whileusing vlfeat (Issue #22625)

This issue has been solved, I am closing it for now.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lunkyguy** [comment]
I get vlfeat source from officail version，and change your cmakelists.txt like this，and it works.
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/8258498/CMakeLists.txt)

**Comment by LilyWangLL** [comment]
Thanks for your work. I will test today.

**Comment by lunkyguy** [comment]
[vl.zip](https://github.com/microsoft/vcpkg/files/8259550/vl.zip)
I never use email,so I forget leave my all project.
thank you for your contribution！

**Comment by LilyWangLL** [comment]
Hi @lunkyguy, I can't repro this issue on my Linux machine. I can configuare and build CMake Project succeed. I use your provide project [vlfeat_test.zip](https://github.com/microsoft/vcpkg/files/7902221/vlfeat_test.zip).
![image](https://user-images.githubusercontent.com/94091114/158561763-ed481200-111f-4421-9e2a-f49ef064f239.png)
There are some change about `generic.c` in `expose_missing_symbols.patch` of vlfeat, I'm not sure if these changes is related with your error. 
```
diff --git a/vl/generic.c b/vl/generic.c
index c6f84a9..8617ed2 100644
--- a/vl/generic.c
+++ b/vl/generic.c
@@ -1513,13 +1513,13 @@ vl_thread_specific_state_delete (VlThreadState * self)
  */
 
 #if (defined(VL_OS_LINUX) || defined(VL_OS_MACOSX)) && defined(VL_COMPILER_GNUC)
-static void vl_constructor () __attribute__ ((constructor)) ;
-static void vl_destructor () __attribute__ ((destructor))  ;
+//static void vl_constructor () __attribute__ ((constructor)) ;
+//static void vl_destructor () __attribute__ ((destructor))  ;
 #endif
 
 #if defined(VL_OS_WIN)
-static void vl_constructor () ;
-static void vl_destructor () ;
+//static void vl_constructor () ;
+//static void vl_destructor () ;
 
 BOOL WINAPI DllMain(
     HINSTANCE hinstDLL,  // handle to DLL module
@@ -1563,7 +1563,7 @@ BOOL WINAPI DllMain(
 /* ---------------------------------------------------------------- */
 
 /** @internal @brief Initialize VLFeat state */
-static void
+void
 vl_constructor (void)
 {
   VlState * state ;
@@ -1637,7 +1637,7 @@ vl_constructor (void)
 }
 
 /** @internal @brief Destruct VLFeat */
-static void
+void
 vl_destructor ()
 {
   VlState * state ;
```

**Comment by lunkyguy** [comment]
thank you ! I should make it clear this is no problem on building and occur on runing,you see my main.cpp,youshould input an image named “1.jpg”,and run command ./run the you will see the bug.I have test it on different version of ubuntu and different machine! at last I find the problem whiling debug it on clion !

**Comment by LilyWangLL** [comment]
Sorry, I input image which named **1.jpg**, and run command `./app`. There are no error and output on machine. 
![image](https://user-images.githubusercontent.com/94091114/158760219-4247d926-dde4-4101-82f8-73bfaee177cb.png)

**Comment by LilyWangLL** [comment]
cc @cenit Could you help take a look this issue? Thanks in advance.

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
This issue hasn’t been updated a long time; if it is still an issue, please reopen it.
