### ISSUE TITLE
vcpkg does not appear as an option in Visual Studio 2022 after vcpkg integrate install

### ISSUE THREAD

**Issue by carmangary** [microsoft/vcpkg#22855]
I have been using vcpkg for years using the old style way to install packages.  I tried to use manifests today using Visual Studio 2022.  I created a manifest but I don't have a vcpkg option in my Visual C++ project properties.

I closed Visual Studio 2022 and reran vcpkg integrate install in and Admin console and then restarted Visual Studio 2022.  I still don't have the vcpkg option under my C++ projects properties.  The only options are General, Advanced, Debugging, and VC++ Directories.

What do I do now?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I use Visual Studio 2022 17.0.0, and I can use VCPKG on Properties of Project like the following picture. Which version of VIsual Studio 2022 are you use?
![image](https://user-images.githubusercontent.com/94091114/151683886-8791038a-d895-4b4f-9b37-34dd5305dd75.png)
![image](https://user-images.githubusercontent.com/94091114/151683935-47b7a7f6-38b0-4d58-87a4-23586d89b5e8.png)\
![image](https://user-images.githubusercontent.com/94091114/151683945-c7fb630f-f302-4d1b-852f-4b439b33e3d4.png)

**Comment by carmangary** [comment]
I have version 17.0.5 of Visual Studio 2022.

Vcpkg does not show up in my menu

**Comment by LilyWangLL** [comment]
Thanks for your reply. Did you use the latest version of VCPKG? Could you update VCPKG and run command `.\vcpkg.exe integrate install` and `.\vcpkg.exe integrate project` on VCPKG? Then open Visual Studio and check properties.

**Comment by carmangary** [comment]
Thank you for your help.  I was using an old version of vcpkg.  Updating it fixed my problem!

**Comment by LilyWangLL** [comment]
This issue has been resolved, so I am closing this issue for now.

**Comment by bwmaples** [comment]
![image](https://user-images.githubusercontent.com/23207913/223679260-fc40cdf6-5051-4de3-8d3d-cb2e10ab641c.png)
I hava the vcpkg option in MyProject, but I still get fatal error C1083: Cannot open include file: 'glib.h': No such file or directory.
However, I have install glib via 
```shell
vcpkg install glib:x86-windows
```

![image](https://user-images.githubusercontent.com/23207913/223680073-3cd462dc-41b3-4b26-9e8e-03f03e167b48.png)

![image](https://user-images.githubusercontent.com/23207913/223680604-6a18a93a-003a-425d-ba8f-80fe185e3d94.png)

**Comment by LilyWangLL** [comment]
Did you run command `./vcpkg integrate install` on your vcpkg?

**Comment by imxtx** [comment]
I followed the instructions exactly, but vs2022 cannot find vspkg and reports: VCPKG not installed on windows

> Did you run command `./vcpkg integrate install` on your vcpkg?

**Comment by vadimax** [comment]
Nothing of mentioned above works.
