### ISSUE TITLE
[pcl] compile error “vtkSmartPointer.h”: No such file or directory

### ISSUE THREAD

**Issue by unnamed2** [microsoft/vcpkg#24439]
**Describe the bug**
```cpp
#include <pcl/visualization/cloud_viewer.h>
```
got fatal error C1083: “vtkSmartPointer.h”: No such file or directory

**Environment**
- OS: Windows11, 22000.613
- Compiler: VS2022(17.1.4)
- package pcl[vtk]

**To Reproduce**
1. ./vcpkg install pcl[vtk]:x64-windows
2. 
```C++
#include <pcl/visualization/cloud_viewer.h>
```
3. compile error

**Expected behavior**
build success

**Failure logs**
A:\vcpkg\installed\x64-windows\include\pcl\visualization\point_cloud_geometry_handlers.h(49,10): fatal error C1083: 无法打开包括文件: “vtkSmartPointer.h”: No such file or directory

**Additional context**

``` bash
vcpkg list
```
```bash
pcl:x64-windows                                    1.12.0#6         Point Cloud Library (PCL) is open source library...
pcl[visualization]:x64-windows                                      Build visualization
pcl[vtk]:x64-windows                                                An alias for visualization
vtk:x64-windows                                    9.0.3-pv5.9.1#10 Software system for 3D computer graphics, image ...
```

vtkSmartPointer.h can be included by 
```C++
#include <vtk-9.0/vtkSmartPointer.h>
```

code in pcl(point_cloud_geometry_handlers.h):
```C++
#include <vtkSmartPointer.h>
#include <vtkPoints.h>
#include <vtkFloatArray.h>
```

**Comment by unnamed2** [comment]
and the following is reported by my compiler while #include<pcl/io/pcd_io>
```
A:\vcpkg\installed\x64-windows\include\pcl\io\low_level_io.h(77,16): error C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
```
XD

**Comment by Cheney-W** [comment]
About your repro step 2 and 3, did you do them in a cmake project or a visual studio empty project? Could you please provide me with your repro project?

**Comment by unnamed2** [comment]
@Cheney-W visual studio empty project，Creating a new console application and then replacing the contents of the generated cpp with the following line of code generates such an error.
```C++
#include <pcl/visualization/cloud_viewer.h>
```
I just tried the cmake project and found that the cmake project did not have such a problem.

**Comment by unnamed2** [comment]
[Here's] (https://github.com/unnamed2/ConsoleApplication1) the project I created

**Comment by Cheney-W** [comment]
Thanks for your reply! I could reproduce this issue in my side.

**Comment by Andor233** [comment]
Same here

**Comment by Linhuihang** [comment]
same question i have

**Comment by mcelhennyi** [comment]
This happened to me as well. 1.12.1 build.

**Comment by best-pureer** [comment]
没办法，pcl内部的vtk include path和vcpkg的include格式不适配，只能手动添加vtk的include path和lib path

**Comment by LOUYIJITUAN** [comment]
解决方案（"VS属性设置-通用属性-VC++目录-包含目录"）
添加路径 *\3rdParty\VTK\include\vtk-9.1
-----------------------------------------------------------------
之前配置页信息可能为：
> D:\PCL 1.12.1\include\pcl-1.12
> D:\PCL 1.12.1\3rdParty\Boost\include\boost-1_78
> D:\PCL 1.12.1\3rdParty\Eigen\eigen3
> D:\PCL 1.12.1\3rdParty\FLANN\include
> D:\PCL 1.12.1\3rdParty\Qhull\include
> D:\PCL 1.12.1\3rdParty\OpenNI2\Include
> D:\PCL 1.12.1\3rdParty\VTK\include

修改后的配置页信息
> D:\PCL 1.12.1\include\pcl-1.12
> D:\PCL 1.12.1\3rdParty\Boost\include\boost-1_78
> D:\PCL 1.12.1\3rdParty\Eigen\eigen3
> D:\PCL 1.12.1\3rdParty\FLANN\include
> D:\PCL 1.12.1\3rdParty\Qhull\include
> D:\PCL 1.12.1\3rdParty\OpenNI2\Include
> D:\PCL 1.12.1\3rdParty\VTK\include
> **D:\PCL 1.12.1\3rdParty\VTK\include\vtk-9.1**

**Comment by jimwang118** [comment]
I tested the latest version of `vcpkg`, and this problem should be solved, and the compilation result is normal by referring to the header file `#include <pcl/visualization/cloud_viewer.h>`.

**Comment by bisalgt** [comment]
I am not able to solve this issue in mac m1. Please let me know if any solutions

**Comment by ZhangYazhengCN** [comment]
The version of vcpkg is newest, but still have the same question. Waiting for a solution which needn't import the lib path in the project's property pages. 

notes: windows10, VS2019, manifest mode

**Comment by cenit** [comment]
@Cheney-W the issue is still present in current master. Any idea for a possible solution?

**Comment by njk42** [comment]
Same problem for me.  Win 10, manifest mode, VS2022, MSBuild project.   

The relevant part of my vcpkg.json is:

    {
      "name": "pcl",
      "default-features": true,
      "features": ["visualization", "vtk"]
    }

The issue appears to be that vcpkg installs the missing header in "../vcpkg_installed/<triplet>/<triplet>/include/vtk-9.2" rather than ""../vcpkg_installed/<triplet>/<triplet>/include/" which is the include directory that MSVC is searching.
