### ISSUE TITLE
[gamenetworkingsockets] update to v1.4.0

### ISSUE THREAD

**Issue by s2s-k** [microsoft/vcpkg#24728]
Library name: [GameNetworkingSockets](https://github.com/ValveSoftware/GameNetworkingSockets)

New version number: v1.4.0

https://github.com/ValveSoftware/GameNetworkingSockets/releases/tag/v1.4.0

**Comment by FrankXie05** [comment]
Fixed of #23043
Make sure you are using the latest vcpkg.

**Comment by s2s-k** [comment]
Lol. I thought library updates were independent of vcpkg update in no way. I thought it was taking information from some website, etc.

https://vcpkg.io/en/packages.html still shows version 1.3.0.

Okay, thank you. Updating vcpkg helped.
