### ISSUE TITLE
vcpkg install blaze:x64-windows --head broken

### ISSUE THREAD

**Issue by hkaiser** [Microsoft/vcpkg#2696]
```
>vcpkg.exe install blaze:x64-windows --head
The following packages will be built and installed:
    blaze[core]:x64-windows (from HEAD)
Starting package 1/1: blaze:x64-windows
Building package blaze[core]:x64-windows from HEAD...
-- CURRENT_INSTALLED_DIR=D:/Devel/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Devel/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Devel/vcpkg/packages/blaze_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Devel/vcpkg/buildtrees/blaze
-- CURRENT_PORT_DIR=D:/Devel/vcpkg/ports/blaze/.
-- Downloading https://api.bitbucket.com/2.0/repositories/blaze-lib/blaze/refs/branches/master...
-- Downloading https://api.bitbucket.com/2.0/repositories/blaze-lib/blaze/refs/branches/master... OK
CMake Error at D:/Devel/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:54 (message):
  vcpkg_download_distfile requires a FILENAME argument.
Call Stack (most recent call first):
  D:/Devel/vcpkg/scripts/cmake/vcpkg_from_bitbucket.cmake:159 (vcpkg_download_distfile)
  D:/Devel/vcpkg/ports/blaze/portfile.cmake:3 (vcpkg_from_bitbucket)
  D:/Devel/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package blaze:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: blaze:x64-windows
  Vcpkg version: 0.0.103-2018-01-30-5700754bd11fe9b22728bd8682c9cfe67a69a462

Additionally, attach any relevant sections from the log files above.
```

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! I've fixed `vcpkg_from_bitbucket()`, so building from head should now work correctly.

**Comment by hkaiser** [comment]
Thanks!

**Comment by PavelKisliak** [comment]
@ras0219-msft sorry, but It still doesn't work. I have tried to add my own library from BitBucket and look to Blaze as an example. It seems that Blaze is only one library from BitBucket which added to vcpkg.
