### ISSUE TITLE
vcpkg.targets outputs error message in success case for pwsh.exe search

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg#38502]
**Describe the bug**
When building using scripts\buildsystems\msbuild\vcpkg.targets and using Windows PowerShell (rather than PowerShell Core), the build outputs an error message when it actually succeeds.

**Environment**
- OS: Windows 11
- Compiler: VS 2022 Version 17.9.6

**To Reproduce**
1. Build a vcxproj that imports scripts\buildsystems\msbuild\vcpkg.targets on a system without PowerShell Core installed.
2. See the Build output window in VS.

**Expected behavior**
No error message appears.

**Additional context**
I suspect the code here is the root cause:

```xml
    <!-- Search %PATH% for pwsh.exe if it is available. -->
    <Exec
      Condition="'$(VcpkgXUseBuiltInApplocalDeps)' != 'true'"
      Command="pwsh.exe $(_ZVcpkgAppLocalPowerShellCommonArguments)"
      IgnoreExitCode="true"
      UseCommandProcessor="false">
      <Output TaskParameter="ExitCode"
              PropertyName="_ZVcpkgAppLocalExitCode" />
    </Exec>
```xml

Updating that code to use something like
```
      Command="cmd /c pwsh.exe $(_ZVcpkgAppLocalPowerShellCommonArguments) >NUL 2>&1"
```
appears likely to fix the problem.

**Comment by FrankXie05** [comment]
>the build outputs an error message when it actually succeeds.

@davidmatson Thanks for posting this issue, could you please provide me with the error log you output?

> Command="cmd /c pwsh.exe $(_ZVcpkgAppLocalPowerShellCommonArguments) >NUL 2>&1"

This will only cover up the error but not fix it. 🤔

**Comment by davidmatson** [comment]
>the build outputs an error message when it actually succeeds.
>@ davidmatson Thanks for posting this issue, could you please provide me with the error log you output?

Sure; the error message is simply:
```
'pwsh.exe' is not recognized as an internal or external command,
```

> Command="cmd /c pwsh.exe $(_ZVcpkgAppLocalPowerShellCommonArguments) >NUL 2>&1"
> This will only cover up the error but not fix it. 🤔

I think the problem is just that the current command attempts to invoke a program that may or may not exist, and then uses the exit code to tell whether it did or not, but that command will naturally error out if the program doesn't exist. If the command is intended just to see if it will fail or not, having the "error" message output isn't great.

Another option would be to use where:

```
Command="cmd /c where pwsh.exe $(_ZVcpkgAppLocalPowerShellCommonArguments) >NUL 2>&1"
```

But redirecting stderr is still necessary; where also outputs text to stderr if the program does not exist.
If the goal is to determine whether the command exists, I don't think suppressing error output hides the problem; the problem is the spurious error message in build logs.

**Comment by berryzplus** [comment]
I think the following code can serve as a temporary workaround.
```xml
    <!-- Search %PATH% for pwsh.exe if it is available. -->
    <Exec
      Condition="'$(VcpkgXUseBuiltInApplocalDeps)' != 'true'"
      Command="pwsh.exe $(_ZVcpkgAppLocalPowerShellCommonArguments) 2&gt;NUL"
      IgnoreExitCode="true"
```

`$(_ZVcpkgAppLocalPowerShellCommonArguments)`  may generate output.
Since we only want to ignore the error output, `2>NUL` is preferable to `>NUL 2>&1`.

May I make a pull request?

**Comment by berryzplus** [comment]
This issue may caused by 11610eabb91dc70853081d7be6b064c896863f13(#35012).

`vcpkg.props` defines `$(VcpkgXUseBuiltInApplocalDeps)` as `false`,
but noone defines `$(VcpkgXUseBuiltInApplocalDeps)` as `true`.

**Comment by shadowstormone** [comment]
At line 229, just rename from pwsh.exe to powershell.exe

**Comment by jtafarrelly** [comment]
Any progress for getting a fix merged for this issue yet?

**Comment by VivitionDeveloper** [comment]
I'm getting the same error, but with changing the default log level of minimal to normal, MSBuild tells something more:

```
Target AppLocalFromInstalled:
1>  'pwsh.exe' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  The command "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "myexe.exe" "<exedir>" "<intermediatedir>my.tlog" "<outdir>\vcpkg.applocal.log"
```

But what is in "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\vcpkg\scripts\buildsystems\msbuild\applocal.ps1"?
It looks like a collector of data and some hacks for various things. Piece of the code, omitting terminating SHA:

```
# Note: This is a hack to make Qt5 work.
# Introduced with Qt package version 5.7.1-7
if (Test-Path "$g_install_root\plugins\qtdeploy.ps1") {
    . "$g_install_root\plugins\qtdeploy.ps1"
}

# Note: This is a hack to make OpenNI2 work.
if (Test-Path "$g_install_root\bin\OpenNI2\openni2deploy.ps1") {
    . "$g_install_root\bin\OpenNI2\openni2deploy.ps1"
}

# Note: This is a hack to make Magnum work.
if (Test-Path "$g_install_root\bin\magnum\magnumdeploy.ps1") {
    . "$g_install_root\bin\magnum\magnumdeploy.ps1"
} elseif (Test-Path "$g_install_root\bin\magnum-d\magnumdeploy.ps1") {
    . "$g_install_root\bin\magnum-d\magnumdeploy.ps1"
}

# Note: This is a hack to make Azure Kinect Sensor SDK work.
if (Test-Path "$g_install_root\tools\azure-kinect-sensor-sdk\k4adeploy.ps1") {
    . "$g_install_root\tools\azure-kinect-sensor-sdk\k4adeploy.ps1"
}

resolve($targetBinary)
Write-Verbose $($g_searched | out-string)
```

Can anyone please disable calling things that look more to internal vcpkg stuff than that is something that should be run always. This looks a bit strange.

**Comment by stungeye** [comment]
This issue has now been active for 1.5 years. The bug is still present today when using vcpkg with Visual Studio 17.14.17. I recognized that the bug doesn't actually affect the build, but I'd prefer for my build output to be free of unnecessary warnings/errors.

**Comment by pedro-w** [comment]
I would love to see a fix for this too, there seem to be several potential solutions suggested.

From reading the comments on this issue it seems like it is benign but I don't think that's obvious to anyone who hasn't read them.

Thanks.

**Comment by Dave-Lowndes** [comment]
Affects VS2026 too.

**Comment by DevSolar** [comment]
It would be *really* nice if someone would actually *fix* this. It really doesn't look like rocket science.

**Comment by murshex** [comment]
Microslop please fix it! :D

**Comment by tbarket** [comment]
> [Frank (@FrankXie05)](https://github.com/FrankXie05)
> 
> The cause of the bug lies in the following part.
> 
> https://github.com/microsoft/vcpkg/blob/ad25766aefb5313b6bc4e2a4b78a2946f84fbf66/scripts/buildsystems/msbuild/vcpkg.targets#L226-L231
> 
> At line 229, it incorrectly calls `pwsh.exe` without checking if `pwsh.exe` is included in the `%PATH%`.
> 
> On Windows, when you want to check if a specific command is in the `%PATH%`, you can use the [WHERE](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/where) command.
> 
> By inserting the following code snippet before line 229, the bug can be resolved.
> 
>       Command="where.exe pwsh.exe &gt;NUL 2&gt;&amp;1"
>       IgnoreExitCode="true"
>       UseCommandProcessor="false">
>       <Output TaskParameter="ExitCode"
>               PropertyName="_ZSearchPwshInPathExitCode" />
>     </Exec>
>     
>     <Exec
>       Condition="'$(_ZSearchPwshInPathExitCode)' == '0'"

This is an unsatisfactory solution.  vcpkg installs its own local powershell-core as one of its tools.  I believe it may even install its own local powershell-core even if you already have a global one installed.  Given this, it doesn't make sense for a vcpkg installation script to look in the PATH for powershell-core.  The pwsh.exe call in line 229 needs to call the powershell-core executable in vcpkg/downloads/tools/powershell-core-x.x.x-windows.

This proposal works fine when the user has a global powershell-core installed.  If this is the intent, then powershell-core should be a vcpkg requirement and not a locally-installed tool.  Another way to make this solution work is to add vcpkg/downloads/tools/powershell-core-x.x.x-windows to one's PATH, but of course this requires the user to remember to change his/her PATH when vcpkg updates.
