### ISSUE TITLE
[boost] error: File does not have the expected hash:

### ISSUE THREAD

**Issue by Jono-Moss** [microsoft/vcpkg#39183]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install boost:x64-windows-static
```

### Failure logs

[DEBUG] C:\Users\Dev\Documents\SDKs\vcpkg-2024.05.24\downloads\boostorg-core-boost-1.85.0.tar.gz.4772.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: C:\Users\Dev\Documents\SDKs\vcpkg-2024.05.24\downloads\boostorg-core-boost-1.85.0.tar.gz.4772.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
[DEBUG] D:\a_work\1\s\src\vcpkg\base\downloads.cpp(997):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 4us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 8107us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 989 ms (962060us)

**Comment by dg0yt** [comment]
Already fixed in https://github.com/microsoft/vcpkg/pull/38979.

**Comment by JonLiu1993** [comment]
@Jono-Moss, Please use command "git pull" get the latest vcpkg and try agagin.

**Comment by flappix** [comment]
I still have the problem
```
vcpkg --version
vcpkg package management program version 2999-12-31-unknownhash
```

This is the part of the log file
```
Installing 1/52 boost-core:arm64-linux@1.85.0...
Building boost-core:arm64-linux@1.85.0...
/path/vcpkg/triplets/community/arm64-linux.cmake: info: loaded community triplet from here. Community triplets are not bu
ilt in the curated registry and are thus less likely to succeed.
/home/user/.cache/vcpkg/registries/git-trees/195375664be82cbc16178de90096e451de070d80: info: installing overlay port from here
-- Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz -> boostorg-core-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /path/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /path/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz --create-dirs --output /path/vcpkg/downloads/boostorg-core-boost-1.85.0.tar.gz.10177.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   671629 us
[DEBUG] Trying to hash /path/vcpkg/downloads/boostorg-core-boost-1.85.0.tar.gz.10177.part
[DEBUG] /path/vcpkg/downloads/boostorg-core-boost-1.85.0.tar.gz.10177.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: /path/vcpkg/downloads/boostorg-core-boost-1.85.0.tar.gz.10177.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
```

Any ideas?

**Comment by dg0yt** [comment]
@flappix In manifest mode: Update the baseline in the manifest.
