### ISSUE TITLE
[boost-variant2] Build error on x64-windows

### ISSUE THREAD

**Issue by x3rt** [microsoft/vcpkg#39411]
Package: boost-variant2:x64-windows@1.85.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33521.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: 52be198ec 2024-06-19 (10 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Downloading https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz -> boostorg-variant2-boost-1-1a5fc662.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\src\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\src\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz
[DEBUG] Trying to hash C:\src\vcpkg\downloads\boostorg-variant2-boost-1-1a5fc662.85.0.tar.gz.41268.part
[DEBUG] C:\src\vcpkg\downloads\boostorg-variant2-boost-1-1a5fc662.85.0.tar.gz.41268.part has hash f4f79ab208c534a7e7a285e2722dbe14c7d810a8ad9e73dd2a6de51862b3b08928802251e8661815e5bf9f82eefd10125a984724ae4670823307edc93cd679a8
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz
File: C:\src\vcpkg\downloads\boostorg-variant2-boost-1-1a5fc662.85.0.tar.gz.41268.part
Expected hash: 1a5fc662247f3e8437dfeec552fc3c5c380112db4a2e6b0c9e7abad1c06ec0d07dcbb528c244884f2507ac14174f4db3fadfd211e84d9bcd26a5ab5f33cb4d97
Actual hash: f4f79ab208c534a7e7a285e2722dbe14c7d810a8ad9e73dd2a6de51862b3b08928802251e8661815e5bf9f82eefd10125a984724ae4670823307edc93cd679a8
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 6us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 576us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 817 ms (797555us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  buildtrees/versioning_/versions/boost-variant2/71aeea8a9326c7b978940c83970790090ddcf8f9/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:191 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "chatterino",
  "version": "2.0.0",
  "builtin-baseline": "01f602195983451bc83e72f4214af2cbc495aa94",
  "dependencies": [
    "boost-asio",
    "boost-circular-buffer",
    "boost-foreach",
    "boost-interprocess",
    "boost-signals2",
    "boost-variant",
    {
      "name": "qt5compat",
      "default-features": false,
      "features": [
        "textcodec"
      ]
    },
    {
      "name": "qtbase",
      "default-features": false,
      "features": [
        "concurrent",
        "gui",
        "jpeg",
        "network",
        "openssl",
        "png",
        "widgets"
      ]
    },
    {
      "name": "qtimageformats",
      "default-features": false,
      "features": [
        "webp"
      ]
    },
    "qtsvg"
  ],
  "features": {
    "benchmarks": {
      "description": "Build benchamarks",
      "dependencies": [
        "benchmark"
      ]
    },
    "tests": {
      "description": "Build tests",
      "dependencies": [
        "gtest"
      ]
    }
  }
}

```
</details>

This seems to be the same problem as in #39409 
It seems to try to compare the hash of a `.part` file instead of the complete download
Really frustrating that there isn't a "ignore hashes" option

**Comment by pedrolamarao** [comment]
I am seeing a similar build failure with a dependency on libsodium -- suddenly, SHA512SUM mismatch.

**Comment by dg0yt** [comment]
This issues is already fixed here. boost moved existing git tags instead of making a new patch release. Now you need to move, too.

**Comment by LilyWangLL** [comment]
Closed as duplicate of #39409.

**Comment by x3rt** [comment]
I have no idea how to fix this.
This is a fresh install of vcpkg.
I have `git pull`ed and ran bootstrap multiple times.
Still getting this error
