### ISSUE TITLE
[openimageio] "/utf-8 is required on Windows" error returns with version v3.0.0.3

### ISSUE THREAD

**Issue by crgnam** [microsoft/vcpkg#42327]
### Is your feature request related to a problem? Please describe.

When using Visual Studio 2022, if you include headers from OpenImageIO (such as `OpenImageIO/imagebuf.h`) you get the following compilation error:

```
C:<foo>\out\build\x64-Release\vcpkg_installed\x64-windows\include\OpenImageIO\detail\fmt\base.h(458): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'
```

This appears to be related to https://github.com/microsoft/vcpkg/issues/41405, which was resolved by https://github.com/microsoft/vcpkg/pull/41429.  However looking at the portfile, the change (adding `-DINTERNALIZE_FMT=OFF ` to the portfile.cmake) is still present in the most recent port for version v3.0.0.3, so I am unsure how related it is.

I do not get the issue when compiling with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, which I do using the following commands:

```
mkdir build;
cd build;
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=<path/to/my/vcpkg>/scripts/buildsystems/vcpkg.cmake
cmake --build .
```

### Proposed solution
Unsure? 

### Describe alternatives you've considered
Unsure of alternatives (for time being, I am continuing to use a previous version of OpenImageIO, which works without issue)

### Additional context
[This public repo](https://github.com/crgnam/oiio-utf8-error) contains a minimal working example to reproduce the error.

**Comment by JonLiu1993** [comment]
Fixed by PR #42532

**Comment by LegalizeAdulthood** [comment]
I am also still seeing this error.  Using vcpkg tag `2025.02.14`

```
  main.cpp
C:\legalize\utahcpp\highway\build-highway-fractal-default\vcpkg_installed\x64-windows\include\OpenImageIO\detail\fmt\base.h(458,28): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8' [C:\legalize\utahcpp\highway\build-highway-fractal-default\tools\fractal.vcxproj]
```
