### ISSUE TITLE
[libexif] Build failure

### ISSUE THREAD

**Issue by ojura** [microsoft/vcpkg#44878]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

Package: libexif:x64-windows@0.6.25

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.43.34809.0
-    vcpkg-tool version: 2024-12-09-1005b78fa1bf1dde1a20c2734cba4ea61ca94d9a
    vcpkg-readonly: true
    vcpkg-scripts version: 0c4cf19224a049cf82f4521e29e39f7bd680440c

**To Reproduce**

`vcpkg install `

**Failure logs**

-- Using cached libexif-libexif-v0.6.25.tar.gz.
-- Extracting source C:/Users/Juraj/AppData/Local/vcpkg/downloads/libexif-libexif-v0.6.25.tar.gz
-- Applying patch fix-ssize.patch
-- Using source at C:/myprojf/build/vcpkg_installed/vcpkg/blds/libexif/src/v0.6.25-545c3dff26.clean
-- Found external ninja('1.12.1').
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20240607-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20240607-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.43.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-4-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.037-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.72-2.72-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.17-1.17-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.35-2-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.10.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.6.3-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.013-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.38.2-2-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.5.20240831-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/Juraj/AppData/Local/vcpkg/downloads/tools/msys2/2db36fb050d01f45
-- Generating configure for x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/Users/Juraj/AppData/Local/vcpkg/downloads/tools/msys2/2db36fb050d01f45/usr/bin/bash.exe --noprofile --norc --debug -c "autoreconf -vfi"
    Working Directory: C:/myproj/build/vcpkg_installed/vcpkg/blds/libexif/src/v0.6.25-545c3dff26.clean/
    Error code: 1
    See logs for more information:
      C:\myproj\build\vcpkg_installed\vcpkg\blds\libexif\autoconf-x64-windows-out.log
      C:\myproj\build\vcpkg_installed\vcpkg\blds\libexif\autoconf-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:725 (vcpkg_execute_required_process)
  C:/Users/Juraj/AppData/Local/vcpkg/registries/git-trees/bf2154950d3e61603b13c8e092f6581796fe4dba/portfile.cmake:18 (vcpkg_configure_make)
  scripts/ports.cmake:196 (include)

<details><summary>C:\myproj\build\vcpkg_installed\vcpkg\blds\libexif\autoconf-x64-windows-err.log</summary>

autoreconf-2.72: export WARNINGS=
autoreconf-2.72: Entering directory '.'
autoreconf-2.72: running: autopoint --force
autoreconf-2.72: running: aclocal --force -I auto-m4 -I m4m
autoreconf-2.72: configure.ac: tracing
autoreconf-2.72: running: libtoolize --copy --force
autoreconf-2.72: configure.ac: not using Intltool
autoreconf-2.72: configure.ac: not using Gtkdoc
autoreconf-2.72: running: aclocal --force -I auto-m4 -I m4m
=> found ["s","t","<undef>",@,1,1] for "trace"
=> cname for "trace" is => ref($L{t}) -> ARRAY
autoreconf-2.72: running: /usr/bin/autoconf-2.72 --force
autoreconf-2.72: running: /usr/bin/autoheader-2.72 --force
autoreconf-2.72: running: automake --add-missing --copy --force-missing
configure.ac:77: installing './ar-lib'
configure.ac:76: installing './compile'
configure.ac:78: installing './config.guess'
configure.ac:78: installing './config.sub'
configure.ac:15: installing './install-sh'
configure.ac:15: installing './missing'
Makefile.am: installing './INSTALL'
contrib/examples/Makefile.am: installing './depcomp'
autoreconf-2.72: error: automake terminated by signal: 11

</details>

<details><summary>C:\myproj\build\vcpkg_installed\vcpkg\blds\libexif\autoconf-x64-windows-out.log</summary>

Copying file ABOUT-NLS
Copying file config.rpath
Copying file auto-m4/codeset.m4
Copying file auto-m4/extern-inline.m4
Copying file auto-m4/fcntl-o.m4
Copying file auto-m4/gettext.m4
Copying file auto-m4/glibc2.m4
Copying file auto-m4/glibc21.m4
Copying file auto-m4/iconv.m4
Copying file auto-m4/intdiv0.m4
Copying file auto-m4/intl.m4
Copying file auto-m4/intldir.m4
Copying file auto-m4/intlmacosx.m4
Copying file auto-m4/intmax.m4
Copying file auto-m4/inttypes-pri.m4
Copying file auto-m4/inttypes_h.m4
Copying file auto-m4/lcmessage.m4
Copying file auto-m4/lib-ld.m4
Copying file auto-m4/lib-link.m4
Copying file auto-m4/lib-prefix.m4
Copying file auto-m4/lock.m4
Copying file auto-m4/longlong.m4
Copying file auto-m4/nls.m4
Copying file auto-m4/po.m4
Copying file auto-m4/printf-posix.m4
Copying file auto-m4/progtest.m4
Copying file auto-m4/size_max.m4
Copying file auto-m4/stdint_h.m4
Copying file auto-m4/threadlib.m4
Copying file auto-m4/uintmax_t.m4
Copying file auto-m4/visibility.m4
Copying file auto-m4/wchar_t.m4
Copying file auto-m4/wint_t.m4
Copying file auto-m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'auto-m4'.
libtoolize: copying file 'auto-m4/libtool.m4'
libtoolize: copying file 'auto-m4/ltoptions.m4'
libtoolize: copying file 'auto-m4/ltsugar.m4'
libtoolize: copying file 'auto-m4/ltversion.m4'
libtoolize: copying file 'auto-m4/lt~obsolete.m4'

</details>

**Additional context**

<details><summary>vcpkg.json</summary>

{
  "dependencies": [
    "eigen3",
    "gdal",
    "libgeotiff",
    "proj",
    "ceres",
    "qtbase",
    "qtimageformats",
    "qtsvg",
    "qcustomplot",
    "sqlite3",
    {
      "name": "opencv",
      "default-features": false,
      "features": [
        "contrib"
      ]
    },
    "boost-filesystem",
    "boost-system",
    {
      "name": "boost-iostreams",
      "default-features": false,
      "features": [
        "zlib"
      ]
    },
    "curl",
    "geographiclib",
    "assimp",
    "libexif",
    "libkml",
    "intel-mkl",
    "mbedtls",
    "protobuf",
    "ffmpeg",
    "lua",
    "lastools",
    "tbb",
    "lz4",
    "mbedtls",
    "libheif"
  ]
}

</details>

**Comment by ojura** [comment]
Weirdly enough, if I make an override port containing the exact same port files as of current master (856505bb767458c99d8e3c3ed441f59a058d3687), it works. But, using `    "baseline": "856505bb767458c99d8e3c3ed441f59a058d3687"` in `vcpkg-configuration.json`, it doesn't work. 🤷

**Comment by ojura** [comment]
Just experienced the problem also with the overlay port, so that looks like a false conclusion. Re-running cmake (which in turn reinvoked vcpkg install) seems to make the build succeed.

**Comment by Mengna-Li** [comment]
So your problem has been solved, right?

**Comment by ojura** [comment]
It seems I can mitigate by running vcpkg install a couple of times until code 11 from autoreconf doesn’t happen. 

The issue still happens sporadically. If I figure out how to more consistently reproduce it, I will update.

**Comment by ojura** [comment]
@Mengna-Li to reproduce, it is enough to have "libexif" as a dependency in vcpkg.json.
