### ISSUE TITLE
[rapidjson] cmake warning about 3.10 compatibility

### ISSUE THREAD

**Issue by MarkCallow** [microsoft/vcpkg#45577]
### Operating system

macOS

### Compiler

n/r

### Steps to reproduce the behavior

```Shell
1. Set up a `vcpkg.json` with a feature having a dependency on the `assimp` or `rapidjson` packages. (`assimp` has a dependency on `rapidjson`).

2. Set up a CMake project which has the above feature.

3. cmake . -B build
```

### Failure logs

```
CMake Deprecation Warning at build/macos/vcpkg_installed/arm64-osx/share/rapidjson/RapidJSONConfig.cmake:3 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  /Users/mark/Projects/github/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (_find_package)
  /Applications/CMake.app/Contents/share/cmake-4.0/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)
  build/macos/vcpkg_installed/arm64-osx/share/assimp/assimpConfig.cmake:36 (find_dependency)
  /Users/mark/Projects/github/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (_find_package)
  tests/loadtests/CMakeLists.txt:41 (find_package)
```

### Additional context

This warning started appearing with cmake 3.31 (or possibly 3.29). I have pulled from the vcpkg several times in the weeks since this first appeared but is still happening as of today.

**Comment by Mengna-Li** [comment]
This error has been fixed in rapidjson https://github.com/Tencent/rapidjson/commit/ebd87cb468fb4cb060b37e579718c4a4125416c1, please install the latest rapidjson on vcpkg.

**Comment by MarkCallow** [comment]
This is still a problem. The  upstream fix has not yet made it into the vcpkg package.

Posting this to keep the issue open.

**Comment by MarkCallow** [comment]
The upstream fixed rapidjson has been incorporated into vcpkg. For a while I was misled because I have a `vcpkg-configuration.json` that specifies a `baseline` commit and the upstream update was added after that commit. I was further misled by the fact that every reference I found to `baseline` described it as the minimum version to use not the maximum, which is what it appears to be in practice. Once I updated my `baseline` I got the upstream fix.
