### ISSUE TITLE
[alembic] Cannot open include file 'half.h'

### ISSUE THREAD

**Issue by ennis** [Microsoft/vcpkg#5085]
This snippet:
```cpp
#include <Alembic/Abc/IArchive.h>

int main()
{
    return 0;
}
```
fails to compile because "half.h" is not found (in Alembic/Util/Foundation.h). Tested with both cmake and msbuild on windows.

It seems that the alembic headers include Ilmbase headers without the OpenEXR/ prefix, which is where the Ilmbase package puts them.

**Comment by Voskrese** [comment]
delete in CMakeLists.txt strings 

```
# IlmBase
INCLUDE("./cmake/AlembicIlmBase.cmake")
INCLUDE_DIRECTORIES(${ALEMBIC_ILMBASE_INCLUDE_DIRECTORY})
```

**Comment by Voskrese** [comment]
my port static

```
vcpkg_apply_patches(
    SOURCE_PATH ${SOURCE_PATH}
    PATCHES
#    ${CMAKE_CURRENT_LIST_DIR}/fix-hdf5link.patch
    ${CMAKE_CURRENT_LIST_DIR}/bypass-findhdf5.patch
)



vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
	-DUSE_HDF5=ON
	-DUSE_STATIC_BOOST=ON
	-DOPENEXR_ROOT=${CURRENT_INSTALLED_DIR}
	-DILMBASE_ROOT=${CURRENT_INSTALLED_DIR}
	-DHDF5_ROOT=${CURRENT_INSTALLED_DIR}
	-Wno-dev
	-DUSE_STATIC_HDF5=ON
	-DUSE_TESTS=OFF 
	-DUSE_EXAMPLES=OFF
	-DALEMBIC_ILMBASE_LINK_STATIC=ON
	-DALEMBIC_SHARED_LIBS=OFF
	-DALEMBIC_LIB_USES_BOOST=ON
	-DUSE_BINARIES=OFF

	-DBUILD_SHARED_LIBS=OFF
)



vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH "lib/cmake/Alembic")

vcpkg_copy_pdbs()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)

# Put the license file where vcpkg expects it
file(COPY ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/Alembic/)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/Alembic/LICENSE.txt ${CURRENT_PACKAGES_DIR}/share/Alembic/copyright)
```

**Comment by LarryIII** [comment]
@ennis Thanks for the feedback. This issue was fixed in  https://github.com/Microsoft/vcpkg/pull/6195

**Comment by FishHe** [comment]
The bug still exists for VS2019 x64-windows.
alembic:x64-windows                                1.7.13#1

**Comment by StephanGarbin** [comment]
I can confirm that as well, VS2019, x64-windows. This PR https://github.com/microsoft/vcpkg/pull/6195/files seems to fix the include errors, so there appears to have been a regression.

**Comment by MarekKowalski** [comment]
Thanks for pointing out the fix @StephanGarbin, I can confirm that the issue is still there today.

**Comment by abdurrahmanarikan** [comment]
I still have the same issue on the mac version
`Alembic/1.7.14/Deploy/include/Alembic/Util/Foundation.h:66:10: error: 'half.h' file not found with <angled> include; use "quotes" instead`
