### ISSUE TITLE
VS2019 glbinding hangs at Building x64 windows rel

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#6824]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3268928/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3268929/install-x64-windows-rel-out.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3268930/config-x64-windows-out.log)

As subject states, in VS2019 Community v16.1.2 hangs at step **Building x64-windows-rel**
 - in taskmanager 2 link.exe, 6 MSBuild.exe, a tracker.exe and a vctip.exe are running but not receiving any CPU, Read/Write/Other I/O's - I have let this run for hours overnight before I control-c the  vcpkg running within an "x64 Native Tools Command Prompt for VS 2019" cmd prompt as an administrator.

I don't believe it is a loop, as no I/O or CPU time is being used and my system stays about 84% idle in about 2 minutes once reaching this step, maybe something is not signaling the tracker.exe to let MSBuild, link and vctip to continue on with the next task???? Just an educated guess.

Note: the VS2017 Enterprise  v15.9.12 takes a couple hours to complete the same task, but does complete and the formentioned taskmanager exe's get CPU time and perform actual I/O's, which ultimately installs glbinding properly.

Attached files which may aid in troubleshooting or recognizing the problem.

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.2
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

06/08/2019 17:11:14 D:\GitHub\vs2019
->vcpkg install forge glbinding --keep-going
The following packages will be built and installed:
    forge[core]:x64-windows
   glbinding[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 3/10: glbinding:x64-windows
Building package glbinding[core]:x64-windows...
-- Using cached D:/GitHub/vcpkg.downloads/cginternals-glbinding-v3.1.0.tar.gz
-- Using source at D:/GitHub/vs2019/buildtrees/glbinding/src/v3.1.0-cda543f4bc
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
^C

Thank you and have a wonderful day.

**Comment by dym21** [comment]
I met the same problem, but I don't know how to solve it. Good luck.

**Comment by heydojo** [comment]
Try deleting the buildtrees/glbinding folder along with any other built trees touched by a VS2017 build and try again.

vcpkg build trees tend to be reused unless they are removed.
Something might be stale there.

If it's happening on a clean pull of vcpkg, then here is the offending port: https://github.com/microsoft/vcpkg/tree/master/ports/glbinding
and the port file is here:
https://github.com/microsoft/vcpkg/blob/master/ports/glbinding/portfile.cmake

**Comment by timautry** [comment]
The VS2017 compiles fine, just takes a while, it is using VS2019 that seems to hang up, runs overnight and stops using any computer resources, no CPU, no I/Os, no memory after a out 2 hours, basically it appears to just stop with the aforementioned programs still in task manager not doing anything.
This can be on an existing vcpkg or a completely clean pull built with VS2019.

**Comment by wadereye** [comment]
I have the same problem:
when I use  it in power shell ,it hangs here over 3 hours.
the command as follow:
PS C:\Users\wadereye> vcpkg install osg:x64-windows sqlite3:x64-windows protobuf:x64-windows poco:x64-windows
The following packages are already installed:
    sqlite3[core]:x64-windows
The following packages will be built and installed:
    osg[core]:x64-windows
  * pcre[core]:x64-windows
    poco[core]:x64-windows
    protobuf[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: osg:x64-windows
Building package osg[core]:x64-windows...
-- Using cached C:/learn/cplus/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.3.tar.gz
-- Using source at C:/learn/cplus/vcpkg/buildtrees/osg/src/raph-3.6.3-e8b171e32a
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel

The screen stop here long long time.
if I　use control+c ,and I saw the same notice again.
My Os is Windows 10.and visual studio 2019 16.2 community version
how can i do  then? thanks.

**Comment by mattparks** [comment]
This hanging issue is still around for glbinding, I'm using Visual Studio 2019 Enterprise installing glbinding:x86-windows stick with this output:
```
C:\Windows\system32>vcpkg install glbinding
The following packages will be built and installed:
    glbinding[core]:x86-windows
Starting package 1/1: glbinding:x86-windows
Building package glbinding[core]:x86-windows...
-- Using cached C:/Program Files/vcpkg/downloads/cginternals-glbinding-v3.1.0.tar.gz
-- Using source at C:/Program Files/vcpkg/buildtrees/glbinding/src/v3.1.0-45d093f32f
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel

```

**Comment by timautry** [comment]
For me it appears this issue has been corrected - I'm now on Windows Pro Version 1909 (OS Build 18363.476) and VS 2019 v16.3.9 and it builds flawlessly now - I believe this issue is resolved!

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.3.9
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

SYSTEM@ANDROMEDA 11/13/2019 16:34:50 D:\Git\vs2019
->vcpkg install glbinding
The following packages will be built and installed:
    glbinding[core]:x64-windows
Starting package 1/1: glbinding:x64-windows
Building package glbinding[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/cginternals-glbinding-v3.1.0.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/cginternals-glbinding-v3.1.0.tar.gz
-- Applying patch 0001_force-system-install.patch
-- Applying patch 0002_fix-uwpmacro.patch
-- Applying patch 0003_fix-cmake-configs-paths.patch
-- Applying patch 0004_fix-config-expected-paths.patch
-- Using source at D:/Git/vs2019/buildtrees/glbinding/src/v3.1.0-45d093f32f
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package glbinding[core]:x64-windows... done
Installing package glbinding[core]:x64-windows...
Installing package glbinding[core]:x64-windows... done
Elapsed time for package glbinding:x64-windows: 6.393 min

Total elapsed time: 6.393 min

The package glbinding:x64-windows provides CMake targets:

    find_package(KHRplatform CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glbinding::KHRplatform)

    find_package(glbinding CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glbinding::glbinding)

    find_package(glbinding-aux CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glbinding::glbinding-aux)

**Comment by mattparks** [comment]
`x64-windows-rel`/`x86-windows-rel` still hangs for 6-10 minutes, I would not say that it's been fully resolved.

**Comment by timautry** [comment]
Compared to **never** completing as it was in the past on my machine, 6 to 7 minutes is fixed. Especially when other packages like the opencv with all options, ffmpeg with all options and a few others take well over 30 minutes to close to an hour to complete the compile, link and install.
