### ISSUE TITLE
Package RtMidi always compile to "Dummy Mode"

### ISSUE THREAD

**Issue by 3NdR1m** [microsoft/vcpkg#6993]
RtMidi [requires some information](http://www.music.mcgill.ca/~gary/rtmidi/#compiling) to know whether it must compile for Windows, Linux or MacOS and it seems like it's not getting any and it's always compiling with the Dummy API which is absolutely barren of features.

What I would normally do is:
#define __WINDOWS_MM__
Add winmm.lib

Also, it's probably outdated.

**Comment by cameronwhite** [comment]
Are there any updates on getting the PR merged? I've also encountered this issue

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Comment by gvnnz** [comment]
@LilyWangL I'm afraid the issue is still there on macOS and Linux, RtMidi 5.0.0 and latest version of vcpkg. The list of compiled API is limited to the Dummy one. On Windows, the API is correctly set to Microsoft Multimedia MIDI API (`WINDOWS_MM`) .

**Comment by glaklandy** [comment]
> @LilyWangL I'm afraid the issue is still there on macOS and Linux, RtMidi 5.0.0 and latest version of vcpkg. The list of compiled API is limited to the Dummy one. On Windows, the API is correctly set to Microsoft Multimedia MIDI API (`WINDOWS_MM`) .

I'm still seeing this now. Was this fixed and then broken again? Is there a way around it? I've tried "manually" installing RtMidi (on a Raspberry Pi Zero in my case) using meson and specifying the ALSA and JACK options be supported, but it still compiled with only the RTMIDI_DUMMY API. Very frustrating.
