### ISSUE TITLE
[bullet3] Missing includepath

### ISSUE THREAD

**Issue by chrisaverage** [microsoft/vcpkg#7877]
bullet3 include files are placed in `<vcpkg includes>/bullet/` directory and `<vcpkg includes>` directory is added to the project include paths in Visual Studio project.
Bullet provides a `btBulletCollisionCommon.h` header with common includes in the `<vcpkg includes>/bullet/` directory and this works fine. Unfortunately some bullet headers are not included in that aggregate and have `#include` statements that assume that bullet includes are in the root of the include path without that `bullet/` prefix, which results in compilation error when trying to include these headers.

Example include that causes problem:
`#include <bullet/BulletCollision/CollisionDispatch/btGhostObject.h>`

This header has include statements like `#include "BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h"` which won't work because `bullet/` is missing in front of it.

Can portfile specify to add that `<vcpkg includes>/bullet/` to the VS project's includepath?

The other options I see is either make vcpkg install bullet headers at the top include path without that `bullet/` prefix (which would be somewhat messy) or add that include path manually in the VS project, but that would kinda defeat the purpose of vcpkg, which is supposed to manage these paths.

**Comment by betsch85** [comment]
I've added `vcpkg\installed\x64-windows\include` to the include dirs which let's me do `#include <bullet/BulletCollision/CollisionDispatch/btGhostObject.h>` just fine, the problem arose when I had to add stuff from `vcpkg\buildtrees\bullet3\src\2.88-ef140bce0a\Extras\` to the include dirs since the Extras aren't built and also not installed (i.e. copied to `vcpkg\installed\...`, I then had to replace all `"LinearMath\..."` includes with `<bullet\LinearMath\...>`

Would be nice to have Extras built and installed as well

**Comment by chrisaverage** [comment]
@betsch85 I don't think you understood what I meant. Yes, you can include `<bullet/BulletCollision/CollisionDispatch/btGhostObject.h>` and it is found without problem. The problem is that that `btGhostObject.h` file itself includes files without the `bullet` prefix, so it doesn't compile unless you also add `vcpkg\installed\x64-windows\include\bullet` subdirectory to include paths, which vcpkg doesn't do.

**Comment by stephenjust** [comment]
It might be worth checking if #9098 fixes this issue.

**Comment by penumbra23** [comment]
I think my problem is related to this one. I'm using vcpkg as a submodule and build with CMake. I've created a CMake files that have these lines included:
```sh
# root CMakeLists.txt file
find_package(Bullet CONFIG REQUIRED)

# project CMakeLists.txt file
target_link_libraries(crane PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody BulletCollision BulletInverseDynamics)
```
Generating project files and building on **Windows** works like a charm, but on Ubuntu 18.04 I get the following error on `cmake --build`:

```sh
In file included from /home/ubuntu/project1/vcpkg/installed/x64-linux/include/bullet/btBulletCollisionCommon.h:22:0,
                 from /home/ubuntu/project1/vcpkg/installed/x64-linux/include/bullet/btBulletDynamicsCommon.h:20,
                 from /home/ubuntu/Project/project1/stdafx.h:38,
                 from /home/ubuntu/Project/project1/BaseEvent.cpp:1:
/home/ubuntu/Project/vcpkg/installed/x64-linux/include/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h:77:10: fatal error: LinearMath/btVector3.h: No such file or directory
 #include "LinearMath/btVector3.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Project/CMakeFiles/project1.dir/build.make:62: recipe for target 'Project/CMakeFiles/project1.dir/BaseEvent.cpp.o' failed
make[2]: *** [Project/CMakeFiles/project1.dir/BaseEvent.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'Project/CMakeFiles/project1.dir/all' failed
make[1]: *** [Project/CMakeFiles/project1.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Because `btCollisionWorld.h` includes `LinearMath` without `bullet/`. Someone with a solution to this problem?

**Comment by penumbra23** [comment]
Okay, solved for my case!
Fixed it with manually including the headers. I suppose we'll have to wait for the "vcpkg included" version.
Nvm, still :heart: vcpkg!

**Comment by morphogencc** [comment]
Just ran into the same problem still -- it's be great if vcpkg could just add `vcpkg\installed\x64-windows\include\bullet` to the include path, which would likely solve the problem.

**Comment by glennDittmann** [comment]
+1 for me :D 
@chrisaverage Thanks for the local solution, I was going mad yesterday night.

Hope this get's fixed soon :-)

**Comment by chrisaverage** [comment]
@glennDittmann I contacted bullet people about this two years ago, because I think this is a problem of the library. It just makes bad assumptions about include paths, which it shouldn't. Unfortunately they said it's too much of a change to fix this, so they won't do it or accept a patch.

vcpkg on the other hand still doesn't have an option to add custom include path afaik.

I'd like this to be fixed globally, but unless one of these two above happens only local solutions seem viable. I don't think either will, so it's a real bummer :(

**Comment by glennDittmann** [comment]
Well, sad to hear. But at least, apart from a few issues, vcpkg is out there making library life far more easy ! :D

**Comment by Garciaj007** [comment]
> Just ran into the same problem still -- it's be great if vcpkg could just add `vcpkg\installed\x64-windows\include\bullet` to the include path, which would likely solve the problem.

If you are working w/h VS (which you most likely will) this snippet is useful inside your additional include directories...
`$(VcpkgRoot)\installed\$(VcpkgTriplet)\include\bullet`

**Comment by FrankXie05** [comment]
@chrisaverage  At present, the project of `vcpkg` on VS (I use the `cmake` project) can already recognize that the include file with has no port prefix. I tried two ports `bullet3` and `libtorrent`. :)
![111111111e](https://user-images.githubusercontent.com/65999885/180147871-790acbaa-d932-4e48-afa1-10e246e6e84b.PNG)
![2222222222](https://user-images.githubusercontent.com/65999885/180147878-30639fb9-778e-4cd0-9afd-c8be88d062ba.PNG)

**Comment by chrisaverage** [comment]
@FrankXie05 I don't know what "works fine" for you, but the issue is just as it was back then.

**Comment by FrankXie05** [comment]
@chrisaverage Thanks for your reply, I think your problem is: 
When the project uses the include file provided by `vcpkg: ${CURRENT_PACKAGES_DIR}/include/${PORT}`, it must add the port name at the beginning to recognize the header file.
Is this what you mean? :)

**Comment by chrisaverage** [comment]
I don't use CMake so I don't know where I would put that syntax in, but the gist of the problem is this:

Some libraries, e.g. zlib, just put includes in top level include  dir and user simply does `#include <zlib.h>`. That's a bit messy because it mixes random headers from all libraries in the top level include dir. Can lead to clashes too if two libraries use the same header name.

Some other libraries are more civilized and put their headers in a subdir. For example glew puts them in a GL subdir, freetype in freetype etc. and bullet does that too - puts include files in bullet subdir. You use them by specifying that subdir in the include e.g. `#include <GL/glew.h>`. It's not related to ports or vcpkg at all. That's just what they do regardless and it just so happens that for bullet it's the same dir name as vcpkg port name.

What those good behaving libraries do though is in their headers they use includes that have that subdir name in them or use relative paths. For example freetype uses `#include <freetype/...` form, glm uses relative `#include <../` paths and that works.

What bullet does is it omits that folder name in its includes and just assumes that user will add that subdir to their include paths. That's ok if you specfy your project manually, but breaks with vcpkg because vcpkg just adds the top level path that includes all ports and you can't add custom per port subdir includes.
So an ugly workaround is to add that bullet subdir manually in your build tool's project file. You might be able to do that generically in CMake with those fancy variables, I don't know, but not all build systems support that and I for example have to manually specify whole local path, which is extremely shady and a maintenance burden.

**Comment by neddia** [comment]
I don't know too much about c, but I messed with this problem for a long time and I thought i'd drop what worked for me here as this is the best thread i could find on the issue. I'm using msys2, not vspkg, but i think the problem is for anyone using a package manager. People explained this already but for beginners a more explicit explanation could be helpful. 

# Bullet Physics Include Path Issue
## The Root Problem
The core issue stems from Bullet's header organization:
- Bullet places its headers in a subdirectory (bullet/)
- However, its headers use includes without the bullet/ prefix (e.g., #include "btVector3.h")
- This structure requires the bullet directory to be in the compiler's include path
## Available Solutions
### 1. CMake Solution
You can handle this in two ways with CMake:
#### Direct Path Specification
```cmake
target_include_directories(game PRIVATE C:/msys64/ucrt64/include/bullet)  # Explicitly add bullet subdirectory
```
#### Using CMake's Package Finding
```cmake
find_package(Bullet REQUIRED)
target_include_directories(game PRIVATE ${BULLET_INCLUDE_DIRS})  # CMake finds the path for us
```
### 2. Direct Compiler Solution
You can specify the include path directly with the compiler:
```bash
# MSVC
cl.exe main.cpp /I"C:/path/to/bullet" ...

# GCC/Clang/Others
g++ main.cpp -I"C:/path/to/bullet" ...
```
The -I flag adds the bullet subdirectory to the include path.
## Conclusion
Both approaches effectively address the same underlying issue by directing the compiler to the correct header location when Bullet's internal includes omit the bullet/ directory prefix. While this header organization is considered suboptimal by Bullet's maintainers (as noted in their forum discussions), both the CMake and direct compiler methods provide viable workarounds by explicitly including the correct path.

**Comment by dg0yt** [comment]
There is nothing wrong with the bullet installation. The original question was:

> Can portfile specify to add that `<vcpkg includes>/bullet/` to the VS project's includepath?

The answer is: No. vcpkg doesn't have this capability at the moment, for VS/msbuild integration. This also affects other packages, e.g. opencv4. AFAIU VS user can manually add the required include paths.

**Comment by chrisaverage** [comment]
Yup, it's a bullet issue, not a vcpkg issue. I just asked if vcpkg could provide a workaround.

_"both the CMake and direct compiler methods provide viable workarounds by explicitly including the correct path"_ - That statement is a bit off to say the least. As I mentioned before manually providing a path in a build file is not a great way to deal with it. CMake has find_package, sure, but not everything uses CMake (my project at the time certainly didn't), and not all build systems have an equivalent. Hardcoding a fixed path and checking it in to source control is a definite no no, so a messy scripting at the user side has to be done. Doable as a hack, but highly undesirable.

It's kinda sad that this still goes on 5 years later. It would took maybe half an hour to fix the includes in bullet, but they just refused to do it or accept a patch. I really don't get that.

I guess this is more of a feature request for vcpkg now, so this issue can either be accepted or closed as "won't do". No point in beating a dead horse otherwise.

**Comment by dg0yt** [comment]
Again, the issue is that vcpkg doesn't provide this type of integration for msbuild.
That dead horse can't be beaten enough.

> Yup, it's a bullet issue,

It is NOT a bullet issue. It is also not a port issue.

"The direct compiler method" is not a workaround but simply the lowest level to approach the task. CMake etc. build on top of this.

If somebody wants to go for the lowest level, fine. But there is a reason why CMake et al. exist. Providing include dirs is just one "usage requirement". In general, there is also providing additional compile options, definitions, link libraries. It makes sense to handle this on a "package" level.

> Hardcoding a fixed path and checking it in to source control is a definite no no,

I would be surprised if there isn't at least a variable to avoid hardcoding the variable part of the actual path.

> It would took maybe half an hour to fix the includes in bullet, but they just refused to do it or accept a patch. I really don't get that.

The proposed change to the headers would require changes to CMake config and/or custom find modules, with undesired side effects: The top-level `include/` directory would become the active include dir, and thus using bullet would make all files in this directory available to a user (at least at a different point in the header search path). This would remove most of the isolation offered by installing headers into different subdirs.

**Comment by chrisaverage** [comment]
> It is NOT a bullet issue. It is also not a port issue.

It definitely IS a bullet issue. They make assumptions in their include statements that both top level and a bullet directory are in search paths. That is a false assumption (in case of vcpkg and other managers) and an artificial usage requirement that has absolutely no reason to be there other than "it's already like that and we don't want to fix it".

> I would be surprised if there isn't at least a variable to avoid hardcoding the variable part of the actual path

Well, consider yourself surprised then and maybe brush up on build systems other than CMake. Yes, they exist and there's a lot of them. 

> The proposed change to the headers would require changes to CMake config

The proposed change to headers is that they would use a proper "bullet/something" in includes (they do in some places already! it's just inconsistent across different parts of bullet), not that everything should be moved to top level include. It requires absolutely no changes to CMake, configs or any modules, just a handful of replacements in include statements. How do I know? Because I did it at the time and offered a patch that was rejected.
The isolation would not be removed that way. It would be improved if anything, as you wouldn't have to pollute the global include paths with bullet subdir.

**Comment by dg0yt** [comment]
> They make assumptions in their include statements that both top level and a bullet directory are in search paths.
>
> "bullet/something" in includes (they do in some places already!

~~~
$ grep -ri "include *.bullet/" installed/x64-linux/include/bullet || echo Nope
Nope
~~~

At least as far as bullet itself is concerned, it doesn't seem to need top-level today AFAICS.

> It requires absolutely no changes to CMake, configs or any modules,

~~~
$ grep INTERFACE_INCLUDE_DIRECTORIES installed/x64-linux/share/bullet/Bullet*cmake
installed/x64-linux/share/bullet/Bullet3CommonTargets.cmake:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/bullet"
~~~
would need to change. (Well, vcpkg could fix that easily.)

---

What could be improved in bullet is poor use of `#include "..."`.

~~~
$ grep -ri "include *.bullet" installed/x64-linux/include/bullet | tail -n 1
installed/x64-linux/include/bullet/BulletSoftBody/btDeformableContactProjection.h:#include "BulletDynamics/Featherstone/btMultiBodyConstraint.h"
~~~

IMO this should be one of the following:
~~~
#include "../BulletDynamics/Featherstone/btMultiBodyConstraint.h" // for local search
#include <BulletDynamics/Featherstone/btMultiBodyConstraint.h>    // for proper search path
~~~
with the first variant enabling `#include <bullet/BulletSoftBody/btDeformableContactProjection.h>`. (But this isn't the intended usage anyways.)

**Comment by chrisaverage** [comment]
> Nope

Fair enough. I might have misremembered that part (it's been a while). The issue stands though

> would need to change. (Well, vcpkg could fix that easily.)

Would it? If I understand it correctly this means vcpkg just puts the content of `${_IMPORT_PREFIX}/include/bullet` in the `vcpkg_installed/<triplet>/include/bullet` directory in my project, which seems ok.

> (But this isn't the intended usage anyways.)

What is the intended usage then? Maybe I was just using it wrong.

I currently have a similar issue with the libwebm port. It has a `/include/webm/mkvparser/mkvreader.h` file that includes `/include/webm/mkvparser/mkvparser.h` through include like this `#include "mkvparser/mkvparser.h"`. Just like in bullet this fails to compile unless changed to `#include "../mkvparser/mkvparser.h"` or the `mkvparser` is added to search paths manually.
Am I missing something about how to use these things or are they just poorly designed libs like that?

**Comment by dg0yt** [comment]
> What is the intended usage then? Maybe I was just using it wrong.

IMO the intented usage is implied by the paths used in the headers: You are expected to have the `bullet3` directory in the search path, not in each individual `include` statement.

> I currently have a similar issue with the libwebm port.

I see, `webm` shares the same inefficiency. 

Note that the pattern is not broken - it works as is with the `webm` directory in the search path. But the patterns forces more lookups than necessary. `#include ".."`  searches in the directory of the current file before using the search path. But `mkvparser/mkvparser.h` is not a valid path *relative to* (the directory of) `mkvparser/mkvreader.h`, so the first attempt will always fail.

**Comment by chrisaverage** [comment]
> Note that the pattern is not broken - it works as is with the webm directory in the search path

Well, that's the part that gets broken. vcpkg does not put `webm` in search path and it arguably shouldn't, not to pollute the search path list too much when you use a bunch of libraries.

So if I do `#include <webm/mkvparser/mkvreader.h>` in my project that uses webm it doesn't compile, as the include inside mkvreader.h is broken. I need to manually add `webm` to search paths in my project.

What is the "proper" way to do that e.g. in CMake?
```
find_package (unofficial-libwebm CONFIG REQUIRED)
target_link_libraries (${TARGET_NAME} PUBLIC unofficial::libwebm::libwebm)
target_include_directories (${TARGET_NAME} PRIVATE  ?????? )
```

Same of course with bullet not to stray from the original subject too much.

**Comment by dg0yt** [comment]
> What is the "proper" way to do that e.g. in CMake?

With CMake "targets", it is meant to be enough to do

~~~
find_package(unofficial-libwebm CONFIG REQUIRED)
target_link_libraries(my_target PRIVATE unofficial::libwebm::libwebm)
~~~

as printed by `vcpkg install libwebm`. It is not necessary to call `target_include_directories` - the extra search paths are part of the "usage requirements" propagated by properties of the `unofficial::libwebm::libwebm` "imported target".  

**But here you have a point:** libwebm is built on using `#include <webm/HEADER>`  indeed. This is the pattern shown in https://github.com/webmproject/libwebm/tree/main/webm_parser#building-your-program, and this is implemented in the CMake config. If there is a header which doesn't work, it must be fixed.

**Comment by dg0yt** [comment]
> libwebm is built on using `#include <webm/HEADER>` indeed. This is the pattern shown in https://github.com/webmproject/libwebm/tree/main/webm_parser#building-your-program,

Hm, `webm_parser` and this documentation is the only reference to this syntax - but this component is disabled in the port. 🤔 
Well, off-topic for bullet3.

**Comment by chrisaverage** [comment]
> Well, off-topic for bullet3

Yup, but it's the same in bullet, so this just shows that there's a general pattern in flawed assumptions in those libraries (and I'm guessing there's more like that). Like I mentioned in the original post it would be nice to have a way to workaround it in vcpkg if the includes can't be fixed in the libs themselves for whatever reason. I'll try to reach out to webm folks if it could be improved, but bullet  already refused to do anything about it 5 years ago. Maybe if someone else asked now they'd be willing to play nice ;)

Could an extra include path be specified on the port level somehow or would that require a new feature in vcpkg? Maybe with a CMake port patch? I guess that still wouldn't solve other build systems, but it would be a partial solution.
I'm not that well versed in the port syntax, especially more recent one.

**Comment by chrisaverage** [comment]
Funnily enough there's a `mkvreader.hpp` file in the top directory that just includes `mkvreader/mkvreader.h` and because of how include paths lookup works using this would solve the issue for webm (because it's in the top level dir, that becomes the missing webm directory in the installed port and it would "inject" the webm directory for lookup making the includes in the .h files work). Unfortunately that hpp file is not being copied as part of the library interface. The comment inside says it's obsolete and should't be used, so probably that's why. Soo... there's a bad #include usage, a hpp file provided that solves it and is not being exposed in the library interface. What a mess :)

**Comment by dg0yt** [comment]
> > Hardcoding a fixed path and checking it in to source control is a definite no no,
> 
> I would be surprised if there isn't at least a variable to avoid hardcoding the variable part of the actual path.

I knew it was somewhere in the opencv4 issue, but I found it only now: `$(VcPkgRoot)`. Cf. https://github.com/microsoft/vcpkg/issues/42004#issuecomment-2500246955 how this is suggested to be used for opencv4.
